"""
lyrics_client.py
----------------
Lyrics fetching from LRCLIB (https://lrclib.net) — free, no API key needed.
Also contains the LRC-format parser used to produce timestamped LyricLine objects.

LRCLIB returns:
  - syncedLyrics  : "[mm:ss.xx] line text" format
  - plainLyrics   : plain text fallback

Fallback order: syncedLyrics → plainLyrics → {"not found"}
"""

import base64
import logging
import re
import time
import difflib
from typing import Dict, Optional, Tuple

import httpx
import asyncio

from models import LyricLine, LyricsResponse

logger = logging.getLogger(__name__)

LRCLIB_BASE = "https://lrclib.net/api"
LRC_TIMETAG_RE = re.compile(r"\[(\d+):(\d+\.\d+)\]")

# ─────────────────────────────────────────────────────────────────────────────
# Persistent file cache — data/lyrics/<artist>—<track>.json, never expires
# ─────────────────────────────────────────────────────────────────────────────

import json
import os
import sys

def _lyrics_dir() -> str:
    if getattr(sys, "frozen", False):
        base = os.path.dirname(sys.executable)
    else:
        base = os.path.dirname(os.path.abspath(__file__))
    d = os.path.join(base, "data", "lyrics")
    os.makedirs(d, exist_ok=True)
    return d

def _cache_key(artist: str, track: str) -> str:
    """Human-readable, filesystem-safe key: 'adele—hello'."""
    def safe(s: str) -> str:
        s = s.lower().strip()
        return re.sub(r'[\\/:*?"<>|]', '_', s)
    return f"{safe(artist)}—{safe(track)}"

def _cache_path(key: str) -> str:
    return os.path.join(_lyrics_dir(), f"{key}.json")

# In-memory hot-cache (avoids disk reads on repeated calls within session)
_hot_cache: Dict[str, "LyricsResponse"] = {}

def _get_cached(key: str) -> Optional["LyricsResponse"]:
    # 1. Hot (memory) cache
    if key in _hot_cache:
        return _hot_cache[key]
    # 2. Disk cache
    path = _cache_path(key)
    if os.path.exists(path):
        try:
            with open(path, "r", encoding="utf-8") as f:
                data = json.load(f)
            result = LyricsResponse(**data)
            _hot_cache[key] = result
            return result
        except Exception as e:
            logger.warning("Lyrics disk cache read error (%s): %s", path, e)
    return None

def _set_cache(key: str, value: "LyricsResponse") -> None:
    _hot_cache[key] = value
    path = _cache_path(key)
    try:
        with open(path, "w", encoding="utf-8") as f:
            json.dump(value.model_dump(), f, ensure_ascii=False, indent=2)
        logger.info("Lyrics cached to disk: %s", path)
    except Exception as e:
        logger.warning("Lyrics disk cache write error (%s): %s", path, e)


# ─────────────────────────────────────────────────────────────────────────────
# LRC Parser
# ─────────────────────────────────────────────────────────────────────────────

def parse_lrc(lrc_text: str) -> list[LyricLine]:
    """
    Parse an LRC-format string into a list of LyricLine objects sorted by time.

    LRC format example:
        [00:17.35] Hello, it's me
        [00:22.90] I was wondering if after all these years...
        [01:20.00][02:40.00] Multi-timestamp concatenation
    """
    lines: list[LyricLine] = []
    for raw_line in lrc_text.splitlines():
        raw_line = raw_line.strip()
        tags = LRC_TIMETAG_RE.findall(raw_line)
        if not tags:
            continue
            
        # Extract the pure text by removing all timestamp tags
        text = LRC_TIMETAG_RE.sub("", raw_line).strip()
        
        if text:  # skip empty/instrumental lines
            for minutes, seconds in tags:
                time_ms = int((int(minutes) * 60 + float(seconds)) * 1000)
                lines.append(LyricLine(time_ms=time_ms, text=text))

    return sorted(lines, key=lambda l: l.time_ms)


# ─────────────────────────────────────────────────────────────────────────────
# LRCLIB HTTP calls
# ─────────────────────────────────────────────────────────────────────────────

async def fetch_lyrics_raw(artist: str, track: str) -> Optional[dict]:
    """
    Hit LRCLIB GET /api/get endpoint.
    Returns the raw JSON dict, or None if not found / on HTTP errors.
    """
    params = {
        "artist_name": artist,
        "track_name": track,
    }
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.get(f"{LRCLIB_BASE}/get", params=params)
            if response.status_code == 200:
                return response.json()
            elif response.status_code == 404:
                logger.info("LRCLIB: lyrics not found for '%s' – '%s'", artist, track)
                return None
            else:
                logger.warning(
                    "LRCLIB returned %s for '%s' – '%s'",
                    response.status_code,
                    artist,
                    track,
                )
                return None
    except httpx.RequestError as e:
        logger.error("LRCLIB request error: %s", e)
        return None


async def search_lyrics_raw(query: str) -> Optional[dict]:
    """
    Fallback search using LRCLIB GET /api/search when exact match fails.
    Returns the first result or None.
    """
    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            response = await client.get(f"{LRCLIB_BASE}/search", params={"q": query})
            if response.status_code == 200:
                results = response.json()
                return results[0] if results else None
            return None
    except httpx.RequestError as e:
        logger.error("LRCLIB search error: %s", e)
        return None


# ─────────────────────────────────────────────────────────────────────────────
# Fallback Fetchers (Netease & KuGou)
# ─────────────────────────────────────────────────────────────────────────────

def _is_romanized(artist: str) -> bool:
    """Returns True if the artist name has NO CJK characters (likely pinyin/romanized).
    Examples: 'Da Da Yue Dui', 'Teng Ge Er', 'Jay Chou' → False (Jay Chou has no CJK)
    vs '腰樂隊', '周杰倫' → False, 'The Beatles' → True (but that's fine, they won't be in CN databases)
    """
    return bool(artist) and not re.search(
        r'[\u4e00-\u9fff\u3040-\u30ff\uac00-\ud7af]', artist
    )


def _is_valid_match(query_track: str, result_track: str,
                    query_artist: str = "", result_artist: str = "",
                    target_duration: int = 0, result_duration: int = 0) -> bool:
    """
    Prevent wildly incorrect lyrics matching.
    Handles bilingual titles like 'A Love Letter \u60c5\u4e66' which may appear as
    '\u60c5\u4e66' or 'A Love Letter' in different music databases.
    Also handles Traditional/Simplified Chinese variations.
    """
    def clean(s: str) -> str:
        # Require a space before or after the hyphen to prevent stripping KuGou's "Artist-Track" format
        s = re.sub(r'\(.*?\)|\[.*?\]|\uff08.*?\uff09|\u3010.*?\u3011|\s-.*|-\s.*', '', s)
        # Keep dots: "\u518d.\u89c1" must stay distinct from "\u518d\u89c1" or "\u518d\u89c1\u4e86"
        return re.sub(r'[^\w\.]', '', s).lower()

    def cjk_only(s: str) -> str:
        return re.sub(r'[^\u4e00-\u9fff\u3040-\u30ff\uac00-\ud7af]', '', s)

    def ascii_only(s: str) -> str:
        return re.sub(r'[^a-z0-9]', '', s.lower())

    # --- Artist match confidence ---
    artist_match = "QUESTIONABLE"
    if query_artist and result_artist:
        cjk_a_q = cjk_only(query_artist)
        cjk_a_r = cjk_only(result_artist)
        if cjk_a_q and cjk_a_r:
            if set(cjk_a_q) & set(cjk_a_r):
                artist_match = "STRONG"
            else:
                return False  # Both have CJK but share nothing = different artists
        else:
            ascii_q = ascii_only(query_artist)
            ascii_r = ascii_only(result_artist)
            if ascii_q and ascii_r:
                a_ratio = difflib.SequenceMatcher(None, ascii_q, ascii_r).ratio()
                if a_ratio > 0.4 or ascii_q in ascii_r or ascii_r in ascii_q:
                    artist_match = "STRONG"
                else:
                    return False  # Both have Ascii but share nothing

    c_query = clean(query_track)
    c_res   = clean(result_track)

    def _check_text() -> bool:
        if not c_query or not c_res:
            return True

        # --- Strategy 1: Full text ratio ---
        ratio = difflib.SequenceMatcher(None, c_query, c_res).ratio()
        threshold = 0.72 if ('.' in c_query or len(c_query) <= 4) else 0.35
        if ratio >= threshold:
            return True

        # --- Strategy 2: CJK sub-match ---
        cjk_q, cjk_r = cjk_only(query_track), cjk_only(result_track)
        if cjk_q and cjk_r:
            if difflib.SequenceMatcher(None, cjk_q, cjk_r).ratio() >= 0.85:
                return True
            if cjk_q in cjk_r or cjk_r in cjk_q:
                longer, shorter = max(len(cjk_q), len(cjk_r)), min(len(cjk_q), len(cjk_r))
                if shorter > 0 and longer / shorter >= 2.0:
                    if target_duration > 0 and result_duration > 0 and abs(target_duration - result_duration) <= 3500:
                        return True

        # --- Strategy 3: ASCII sub-match ---
        ascii_q, ascii_r = ascii_only(query_track), ascii_only(result_track)
        if ascii_q and ascii_r and len(ascii_q) >= 4:
            if difflib.SequenceMatcher(None, ascii_q, ascii_r).ratio() >= 0.75:
                return True
            if ascii_q in ascii_r or ascii_r in ascii_q:
                if target_duration > 0 and result_duration > 0 and abs(target_duration - result_duration) <= 3500:
                    return True

        # --- Strategy 4: Duration fingerprint fallback ---
        # Highly dangerous if text is < threshold. 
        if target_duration > 0 and result_duration > 0:
            diff_ms = abs(target_duration - result_duration)
            if artist_match == "STRONG" and diff_ms <= 8000:
                # Artist is unequivocally identical. Allow generous len_ratio for "Live" or "Remix" mismatches
                len_ratio = min(len(c_query), len(c_res)) / max(len(c_query), len(c_res), 1)
                if len_ratio >= 0.6 or len(c_query) == len(c_res):
                    return True
            elif diff_ms <= 3500:
                # Artist is QUESTIONABLE. Extremely restrictive duration mapping to support 
                # Traditional <> Simplified Chinese 1:1 translations (e.g. "好險好險" vs "好险好险").
                if len(c_query) == len(c_res) and len(c_query) > 0:
                    if len(c_query) <= 3 or (set(c_query) & set(c_res)):
                        return True

        if artist_match == "STRONG":
            logger.info(f"LYRICS REJECTED (STRONG ARTIST): '{query_artist} - {query_track}' vs '{result_artist} - {result_track}' (diff: {abs(target_duration-result_duration)}ms, text_ratio: {difflib.SequenceMatcher(None, c_query, c_res).ratio():.2f})")

        return False

    is_text_match = _check_text()

    # CRITICAL: If the artist is highly questionable (e.g. cross-script "Kawa" vs "张栋梁" or "Da Da Yue Dui" vs "顽乐团"),
    # we CANNOT trust a simple track text match (like "无双"). 
    # It must be mathematically verified by audio duration fingerprint!
    if is_text_match and artist_match == "QUESTIONABLE":
        if target_duration > 0 and result_duration > 0:
            # Dynamically calculate the margin based on structural Pinyin matching.
            # E.g. "Da Da Yue Dui" (4 words) vs "达达乐队" (4 chars) -> High probability Pinyin match!
            # E.g. "Da Da Yue Dui" (4 words) vs "顽乐团" (3 chars) -> Near zero probability, lock it down!
            q_words = [w for w in re.split(r'[^a-zA-Z0-9]', query_artist) if w]
            r_cjk = cjk_only(result_artist)
            
            is_pinyin_match = False
            if len(q_words) > 0 and r_cjk and len(q_words) == len(r_cjk):
                is_pinyin_match = True
                
            if not is_pinyin_match:
                # If the artist is entirely unverified (No text overlap + No Pinyin structure match),
                # ONLY allow the 1.5s fallback if the track is uniquely long enough.
                # Extremely short generic names (<=3 chars like "无双", "等待") will endlessly
                # collide with random live covers on the Netease track-only search fallback.
                if len(c_query) <= 3:
                    return False
                margin = 1500
            else:
                margin = 3500
            
            if abs(target_duration - result_duration) > margin:
                return False

    return is_text_match

async def search_lyrics_netease(artist: str, track: str, duration_ms: int = 0) -> Optional[str]:
    """Fallback 1: Search Netease Cloud Music (163) for LRC lyrics."""
    def cjk_only(s):
        # Keep dots: "再.见" must be searched as "再.见", not "再见"
        return re.sub(r'[^\u4e00-\u9fff\u3040-\u30ff\uac00-\ud7af\.]', '', s).strip()
    def ascii_only(s):
        return re.sub(r'[^a-zA-Z0-9 ]', '', s).strip()

    cjk_part  = cjk_only(track)
    ascii_part = ascii_only(track)

    # When artist is romanized (pinyin like 'Da Da Yue Dui'), Netease won't recognise
    # it — skip artist-prefixed queries and go straight to track-only searches.
    romaji = _is_romanized(artist)

    # Always include the artist + track query as the primary search term.
    # We still try the artist-prefixed search even if romanized, as it 
    # fixes searches for English band names like 'sadog'.
    queries: list[str] = [f"{artist} {track}"]
    
    # Fallback to track name only (useful for pinyin artists Netease might not know)
    queries.append(track)
    
    if cjk_part and cjk_part != track:
        queries.insert(len(queries) - 1, f"{artist} {cjk_part}")
        queries.insert(len(queries) - 1, cjk_part)
        
    if ascii_part and ascii_part.lower() != track.lower() and len(ascii_part) >= 3:
        queries.append(ascii_part)

    # Deduplicate while preserving order
    seen: set = set()
    queries = [q for q in queries if not (q in seen or seen.add(q))]  # type: ignore

    search_url = "https://music.163.com/api/search/get/web"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36",
        "Referer": "https://music.163.com/"
    }

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            cjk_title = cjk_only(track)
            limit = 100 if (romaji or len(cjk_title) <= 3) else 8
            
            reqs = [
                client.get(search_url, params={"s": q, "type": 1, "limit": limit}, headers=headers)
                for q in queries
            ]
            responses = await asyncio.gather(*reqs, return_exceptions=True)

            for query, res in zip(queries, responses):
                if isinstance(res, Exception) or res.status_code != 200:
                    continue
                data = res.json()

                songs = data.get("result", {}).get("songs", [])
                if not songs:
                    continue

                for song in songs:
                    song_name = song.get("name", "")
                    song_dur = song.get("duration", 0)
                    # Collaborator ASCII Poisoning fix: Evaluate ONLY the primary artist.
                    # e.g., "汉堡黄" + "Luna Li" -> "汉堡黄". 
                    # If we merge them to "汉堡黄LunaLi", "LunaLi" forces the strict ASCII check
                    # against "puppiebelly", causing an instant false negative.
                    artists_list = song.get("artists", [])
                    song_artists = artists_list[0].get("name", "") if artists_list else ""

                    if not _is_valid_match(track, song_name, artist, song_artists, duration_ms, song_dur):
                        continue

                    song_id = song["id"]
                    lyric_url = "https://music.163.com/api/song/lyric"
                    l_params = {"id": song_id, "lv": 1, "tv": -1, "kv": 1}
                    l_res = await client.get(lyric_url, params=l_params, headers=headers)
                    l_data = l_res.json()

                    lrc = l_data.get("lrc", {}).get("lyric", "")
                    if lrc:
                        logger.info("Netease lyrics found via query '%s' for '%s - %s'", query, artist, track)
                        return lrc
    except Exception as e:
        logger.warning("Netease fallback error for '%s - %s': %s", artist, track, e)

    return None

async def search_lyrics_kugou(artist: str, track: str, duration_ms: int = 0) -> Optional[str]:
    """
    Search KuGou for raw LRC text. Works well for tracks not on LRCLIB.
    """
    def cjk_only(s):
        # Keep dots: "再.见" must be searched as "再.见", not "再见"
        return re.sub(r'[^\u4e00-\u9fff\u3040-\u30ff\uac00-\ud7af\.]', '', s).strip()
    def ascii_only(s):
        return re.sub(r'[^a-zA-Z0-9 ]', '', s).strip()

    cjk_part  = cjk_only(track)
    ascii_part = ascii_only(track)
    romaji = _is_romanized(artist)

    queries: list[str] = []
    if not romaji:
        queries.append(f"{artist} {track}")
    queries.append(track)
    if cjk_part and cjk_part != track:
        if not romaji:
            queries.insert(len(queries) - 1, f"{artist} {cjk_part}")
        queries.insert(len(queries) - 1, cjk_part)
    if ascii_part and ascii_part.lower() != track.lower() and len(ascii_part) >= 3:
        queries.append(ascii_part)

    seen: set = set()
    queries = [q for q in queries if not (q in seen or seen.add(q))]  # type: ignore

    search_url = "http://songsearch.kugou.com/song_search_v2"
    headers = {
        "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36"
    }

    try:
        async with httpx.AsyncClient(timeout=10.0) as client:
            cjk_title = cjk_only(track)
            limit = 10 if (romaji or len(cjk_title) <= 3) else 5
            reqs = [
                client.get(search_url, params={
                    "keyword": q, "page": 1, "pagesize": limit, "platform": "WebFilter"
                }, headers=headers)
                for q in queries
            ]
            responses = await asyncio.gather(*reqs, return_exceptions=True)

            for query, res in zip(queries, responses):
                if isinstance(res, Exception) or res.status_code != 200:
                    continue
                data = res.json()
                songs = data.get("data", {}).get("lists", [])
                if not songs:
                    continue
                for song in songs:
                    song_name = song.get("SongName", "")
                    song_dur = song.get("Duration", 0) * 1000
                    
                    # Collaborator ASCII Poisoning fix: Split by "、" and take the first primary artist.
                    raw_singer = song.get("SingerName", "")
                    artist_name = raw_singer.split("、")[0] if "、" in raw_singer else raw_singer

                    if not _is_valid_match(track, song_name, artist, artist_name, duration_ms, song_dur):
                        continue

                    filehash = song.get("FileHash")
                    artist_name = song.get("SingerName")
                    duration = song.get("Duration", 0) * 1000
                    album_id = song.get("ID")

                    l_search_url = "http://krcs.kugou.com/search"
                    l_params = {
                        "ver": 1, "man": "yes", "client": "mobi",
                        "keyword": f"{artist_name} - {song_name}",
                        "duration": duration, "hash": filehash, "album_audio_id": album_id
                    }
                    l_res = await client.get(l_search_url, params=l_params, headers=headers)
                    l_data = l_res.json()
                    candidates = l_data.get("candidates", [])
                    if not candidates:
                        continue

                    accesskey = candidates[0].get("accesskey")
                    lrc_id = candidates[0].get("id")

                    dl_url = "http://lyrics.kugou.com/download"
                    dl_params = {
                        "ver": 1, "client": "pc", "id": lrc_id,
                        "accesskey": accesskey, "fmt": "lrc", "charset": "utf8"
                    }
                    dl_res = await client.get(dl_url, params=dl_params, headers=headers)
                    dl_data = dl_res.json()

                    lrc_b64 = dl_data.get("content", "")
                    if lrc_b64:
                        logger.info("KuGou lyrics found via query '%s' for '%s - %s'", query, artist, track)
                        return base64.b64decode(lrc_b64).decode('utf-8')

    except Exception as e:
        logger.warning("KuGou fallback error for '%s - %s': %s", artist, track, e)

    return None

# ─────────────────────────────────────────────────────────────────────────────
# Public interface
# ─────────────────────────────────────────────────────────────────────────────

async def get_lyrics(artist: str, track: str, duration_ms: int = 0) -> LyricsResponse:
    """
    Fetch and parse lyrics for a given artist + track name.

    Strategy:
      1. Check in-memory cache
      2. Exact search: LRCLIB /api/get
      3. Fuzzy fallback: LRCLIB /api/search
      4. Return empty LyricsResponse if nothing found
    """
    # Fix for Spotify -> Netease/KuGou Pinyin blindspots.
    # Chinese streaming APIs often return literally ZERO results for Pinyin aliases.
    PINYIN_ARTIST_MAP = {
        "instinkto industrio": "本能实业",
        "zhu zheng ting": "朱正廷",
        "zhu ming ying4": "朱明瑛",
        "zhu ming ying3": "朱明瑛",
        "zhu ming ying2": "朱明瑛",
        "zhu ming ying": "朱明瑛",
        "zhu hai yin4": "朱海茵",
        "zhu hai yin3": "朱海茵",
        "zhu hai yin2": "朱海茵",
        "zhu hai yin": "朱海茵",
        "zhou ye": "周野",
        "zhou xun": "周迅",
        "zhou xuan4": "周璇",
        "zhou xuan3": "周璇",
        "zhou xuan2": "周璇",
        "zhou xuan": "周璇",
        "zhou shen3": "周深",
        "zhou shen2": "周深",
        "zhou shen": "周深",
        "zhou hui min": "周慧敏",
        "zhou guo xian4": "周国贤",
        "zhou guo xian3": "周国贤",
        "zhou guo xian2": "周国贤",
        "zhou guo xian": "周国贤",
        "zhou bo hao": "周柏豪",
        "zheng zhong ji": "郑中基",
        "zheng xiu wen2": "郑秀文",
        "zheng xiu wen": "郑秀文",
        "zheng jun3": "郑钧",
        "zheng jun2": "郑钧",
        "zheng jun": "郑钧",
        "zheng jin yi4": "郑进一",
        "zheng jin yi3": "郑进一",
        "zheng jin yi2": "郑进一",
        "zheng jin yi": "郑进一",
        "zhen ni4": "甄妮",
        "zhen ni3": "甄妮",
        "zhen ni2": "甄妮",
        "zhen ni": "甄妮",
        "zhen hua4": "甄华",
        "zhen hua3": "甄华",
        "zhen hua2": "甄华",
        "zhen hua": "甄华",
        "zhao zhao3": "赵昭",
        "zhao zhao2": "赵昭",
        "zhao zhao": "赵昭",
        "zhao peng4": "赵鹏",
        "zhao peng3": "赵鹏",
        "zhao peng2": "赵鹏",
        "zhao peng": "赵鹏",
        "zhao li ying": "赵丽颖",
        "zhao lei3": "赵雷",
        "zhao lei2": "赵雷",
        "zhao lei": "赵雷",
        "zhao dan4": "赵丹",
        "zhao dan3": "赵丹",
        "zhao dan2": "赵丹",
        "zhao dan": "赵丹",
        "zhang yu qi2": "张钰琪",
        "zhang yu qi": "张钰琪",
        "zhang xue you3": "张学友",
        "zhang xue you2": "张学友",
        "zhang xue you": "张学友",
        "zhang xiu qing4": "张秀卿",
        "zhang xiu qing3": "张秀卿",
        "zhang xiu qing2": "张秀卿",
        "zhang xiu qing": "张秀卿",
        "zhang xiao hou3": "张小厚",
        "zhang xiao hou2": "张小厚",
        "zhang xiao hou": "张小厚",
        "zhang wei jian": "张卫健",
        "zhang qing fang4": "张清芳",
        "zhang qing fang3": "张清芳",
        "zhang qing fang2": "张清芳",
        "zhang qing fang": "张清芳",
        "zhang liang ying2": "张靓颖",
        "zhang liang ying": "张靓颖",
        "zhang jing xuan": "张敬轩",
        "zhang ji ting4": "张继聪",
        "zhang ji ting3": "张继聪",
        "zhang ji ting2": "张继聪",
        "zhang ji ting": "张继聪",
        "zhang hui4": "张慧",
        "zhang hui3": "张慧",
        "zhang hui2": "张慧",
        "zhang hui": "张慧",
        "zhang guo rong": "张国荣",
        "zhang de lan": "张德兰",
        "zhang chu3": "张楚",
        "zhang chu2": "张楚",
        "zhang chu": "张楚",
        "zhan ya wen4": "詹雅雯",
        "zhan ya wen3": "詹雅雯",
        "zhan ya wen2": "詹雅雯",
        "zhan ya wen": "詹雅雯",
        "zeng xin mei4": "曾心梅",
        "zeng xin mei3": "曾心梅",
        "zeng xin mei2": "曾心梅",
        "zeng xin mei": "曾心梅",
        "zeng wei zhong2": "曾维忠",
        "zeng wei zhong": "曾维忠",
        "yuan ya wei2": "袁娅维",
        "yuan ya wei": "袁娅维",
        "yuan xiao di4": "袁小迪",
        "yuan xiao di3": "袁小迪",
        "yuan xiao di2": "袁小迪",
        "yuan xiao di": "袁小迪",
        "yu wen wen2": "于文文",
        "yu wen wen": "于文文",
        "yu wen le": "余文乐",
        "yu cheng qing4": "庾澄庆",
        "yu cheng qing3": "庾澄庆",
        "yu cheng qing2": "庾澄庆",
        "yu cheng qing": "庾澄庆",
        "you zhang jing": "尤长靖",
        "you ya4": "尤雅",
        "you ya3": "尤雅",
        "you ya2": "尤雅",
        "you ya": "尤雅",
        "you min4": "尤敏",
        "you min3": "尤敏",
        "you min2": "尤敏",
        "you min": "尤敏",
        "yoga lin3": "林宥嘉",
        "yoga lin2": "林宥嘉",
        "yoga lin": "林宥嘉",
        "ying tang shao nv": "硬糖少女303",
        "yin xia4": "银霞",
        "yin xia3": "银霞",
        "yin xia2": "银霞",
        "yin xia": "银霞",
        "yin shi4": "殷诗",
        "yin shi3": "殷诗",
        "yin shi2": "殷诗",
        "yin shi": "殷诗",
        "yin guang4": "银矿",
        "yin guang3": "银矿",
        "yin guang2": "银矿",
        "yin guang": "银矿",
        "yida huang2": "黄义达",
        "yida huang": "黄义达",
        "yi yang qian xi": "易烊千玺",
        "yi neng jing4": "伊能静",
        "yi neng jing3": "伊能静",
        "yi neng jing2": "伊能静",
        "yi neng jing": "伊能静",
        "yellow2": "黄宣",
        "yellow": "黄宣",
        "ye zhen tang4": "叶振棠",
        "ye zhen tang3": "叶振棠",
        "ye zhen tang2": "叶振棠",
        "ye zhen tang": "叶振棠",
        "ye shi rong2": "叶世荣",
        "ye shi rong": "叶世荣",
        "ye qian wen": "叶倩文",
        "ye qi tian4": "叶启田",
        "ye qi tian3": "叶启田",
        "ye qi tian2": "叶启田",
        "ye qi tian": "叶启田",
        "ye li yi4": "叶丽仪",
        "ye li yi3": "叶丽仪",
        "ye li yi2": "叶丽仪",
        "ye li yi": "叶丽仪",
        "ye feng4": "叶枫",
        "ye feng3": "叶枫",
        "ye feng2": "叶枫",
        "ye feng": "叶枫",
        "yao li4": "姚莉",
        "yao li3": "姚莉",
        "yao li2": "姚莉",
        "yao li": "姚莉",
        "yao band": "腰乐队",
        "yang zhe4": "杨哲",
        "yang zhe3": "杨哲",
        "yang zhe2": "杨哲",
        "yang zhe": "杨哲",
        "yang ying": "杨英",
        "yang qian hua": "杨千嬅",
        "yang nai wen": "杨乃文",
        "yang mi": "杨幂",
        "yang lin4": "杨林",
        "yang lin3": "杨林",
        "yang lin2": "杨林",
        "yang lin": "杨林",
        "yang cheng lin": "杨丞琳",
        "yan yi ge2": "颜一歌",
        "yan yi ge": "颜一歌",
        "yan jue2": "颜爵",
        "yan jue": "颜爵",
        "xue zhi qian2": "薛之谦",
        "xue zhi qian": "薛之谦",
        "xue kai qi2": "薛凯琪",
        "xue kai qi": "薛凯琪",
        "xu zhi an2": "许志安",
        "xu zhi an": "许志安",
        "xu xiao feng4": "徐小凤",
        "xu xiao feng3": "徐小凤",
        "xu xiao feng2": "徐小凤",
        "xu xiao feng": "徐小凤",
        "xu wei3": "许巍",
        "xu wei2": "许巍",
        "xu wei": "许巍",
        "xu song2": "许嵩",
        "xu song": "许嵩",
        "xu ru yun": "许茹芸",
        "xu jia ying2": "徐佳莹",
        "xu jia ying": "徐佳莹",
        "xu feng yi4": "许凤仪",
        "xu feng yi3": "许凤仪",
        "xu feng yi2": "许凤仪",
        "xu feng yi": "许凤仪",
        "xiu lan ya": "秀兰玛雅",
        "xiu lan ma ya4": "秀兰玛雅",
        "xiu lan ma ya3": "秀兰玛雅",
        "xiu lan ma ya2": "秀兰玛雅",
        "xiu lan ma ya": "秀兰玛雅",
        "xin xiao qi": "辛晓琪",
        "xin ku zi": "新裤子",
        "xie ting feng": "谢霆锋",
        "xie jin yan4": "谢金燕",
        "xie jin yan3": "谢金燕",
        "xie jin yan2": "谢金燕",
        "xie jin yan": "谢金燕",
        "xie an qi2": "谢安琪",
        "xie an qi": "谢安琪",
        "xiao zi3": "小紫",
        "xiao zi2": "小紫",
        "xiao zi": "小紫",
        "xiao zhou3": "小周",
        "xiao zhou2": "小周",
        "xiao zhou": "小周",
        "xiao zhong3": "小中",
        "xiao zhong2": "小中",
        "xiao zhong": "小中",
        "xiao zheng3": "小郑",
        "xiao zheng2": "小郑",
        "xiao zheng": "小郑",
        "xiao zhen3": "小珍",
        "xiao zhen2": "小珍",
        "xiao zhen": "小珍",
        "xiao zha3": "小扎",
        "xiao zha2": "小扎",
        "xiao zha": "小扎",
        "xiao ze3": "小泽",
        "xiao ze2": "小泽",
        "xiao ze": "小泽",
        "xiao za3": "小扎",
        "xiao za2": "小扎",
        "xiao za": "小扎",
        "xiao yun6": "小芸",
        "xiao yun5": "小云",
        "xiao yun4": "小芸",
        "xiao yun3": "小云",
        "xiao yun2": "小芸",
        "xiao yun": "小云",
        "xiao yong3": "小勇",
        "xiao yong2": "小勇",
        "xiao yong": "小勇",
        "xiao ying3": "小英",
        "xiao ying2": "小英",
        "xiao ying": "小英",
        "xiao ye3": "小叶",
        "xiao ye2": "小叶",
        "xiao ye": "小叶",
        "xiao yang3": "小洋",
        "xiao yang2": "小洋",
        "xiao yang": "小洋",
        "xiao yan3": "小燕",
        "xiao yan2": "小燕",
        "xiao yan": "小燕",
        "xiao ya3": "小雅",
        "xiao ya2": "小雅",
        "xiao ya": "小雅",
        "xiao xue3": "小雪",
        "xiao xue2": "小雪",
        "xiao xue": "小雪",
        "xiao xu3": "小徐",
        "xiao xu2": "小徐",
        "xiao xu": "小徐",
        "xiao xiu3": "小秀",
        "xiao xiu2": "小秀",
        "xiao xiu": "小秀",
        "xiao xiong3": "小熊",
        "xiao xiong2": "小熊",
        "xiao xiong": "小熊",
        "xiao xin3": "小心",
        "xiao xin2": "小心",
        "xiao xin": "小心",
        "xiao xia6": "小霞",
        "xiao xia5": "小夏",
        "xiao xia4": "小霞",
        "xiao xia3": "小夏",
        "xiao xia2": "小霞",
        "xiao xia": "小夏",
        "xiao xi6": "小西",
        "xiao xi5": "小西",
        "xiao xi4": "小西",
        "xiao xi3": "小西",
        "xiao xi2": "小西",
        "xiao xi": "小西",
        "xiao wu3": "小吴",
        "xiao wu2": "小吴",
        "xiao wu": "小吴",
        "xiao wei4": "小伟",
        "xiao wei3": "小伟",
        "xiao wei2": "小伟",
        "xiao wei": "小伟",
        "xiao wa3": "小瓦",
        "xiao wa2": "小瓦",
        "xiao wa": "小瓦",
        "xiao tu3": "小土",
        "xiao tu2": "小土",
        "xiao tu": "小土",
        "xiao tian3": "小天",
        "xiao tian2": "小天",
        "xiao tian": "小天",
        "xiao tang3": "小唐",
        "xiao tang2": "小唐",
        "xiao tang": "小唐",
        "xiao ta3": "小塔",
        "xiao ta2": "小塔",
        "xiao ta": "小塔",
        "xiao sun3": "小孙",
        "xiao sun2": "小孙",
        "xiao sun": "小孙",
        "xiao shui3": "小水",
        "xiao shui2": "小水",
        "xiao shui": "小水",
        "xiao shi3": "小石",
        "xiao shi2": "小石",
        "xiao shi": "小石",
        "xiao shan3": "小山",
        "xiao shan2": "小山",
        "xiao shan": "小山",
        "xiao sha3": "小莎",
        "xiao sha2": "小莎",
        "xiao sha": "小莎",
        "xiao sa3": "小萨",
        "xiao sa2": "小萨",
        "xiao sa": "小萨",
        "xiao re3": "小热",
        "xiao re2": "小热",
        "xiao re": "小热",
        "xiao qu3": "小曲",
        "xiao qu2": "小曲",
        "xiao qu": "小曲",
        "xiao qiu3": "小秋",
        "xiao qiu2": "小秋",
        "xiao qiu": "小秋",
        "xiao qing6": "小青",
        "xiao qing5": "小青",
        "xiao qing4": "小青",
        "xiao qing3": "小青",
        "xiao qing2": "小青",
        "xiao qing": "小青",
        "xiao qin3": "小琴",
        "xiao qin2": "小琴",
        "xiao qin": "小琴",
        "xiao po3": "小婆",
        "xiao po2": "小婆",
        "xiao po": "小婆",
        "xiao ping6": "小平",
        "xiao ping5": "小平",
        "xiao ping4": "小平",
        "xiao ping3": "小平",
        "xiao ping2": "小平",
        "xiao ping": "小平",
        "xiao nuo3": "小诺",
        "xiao nuo2": "小诺",
        "xiao nuo": "小诺",
        "xiao ning3": "小宁",
        "xiao ning2": "小宁",
        "xiao ning": "小宁",
        "xiao niang3": "小娘",
        "xiao niang2": "小娘",
        "xiao niang": "小娘",
        "xiao nan3": "小南",
        "xiao nan2": "小南",
        "xiao nan": "小南",
        "xiao mu5": "小慕",
        "xiao mu4": "小木",
        "xiao mu3": "小慕",
        "xiao mu2": "小慕",
        "xiao mu2": "小木",
        "xiao mu": "小木",
        "xiao min3": "小民",
        "xiao min2": "小民",
        "xiao min": "小民",
        "xiao mi3": "小米",
        "xiao mi2": "小米",
        "xiao mi": "小米",
        "xiao mei3": "小妹",
        "xiao mei2": "小妹",
        "xiao mei": "小妹",
        "xiao ma4": "小妈",
        "xiao ma3": "小马",
        "xiao ma3": "小妈",
        "xiao ma2": "小马",
        "xiao ma2": "小妈",
        "xiao ma": "小马",
        "xiao lv3": "小绿",
        "xiao lv2": "小绿",
        "xiao lv": "小绿",
        "xiao luo3": "小罗",
        "xiao luo2": "小罗",
        "xiao luo": "小罗",
        "xiao lu3": "小路",
        "xiao lu2": "小路",
        "xiao lu": "小路",
        "xiao long3": "小龙",
        "xiao long2": "小龙",
        "xiao long": "小龙",
        "xiao ling3": "小玲",
        "xiao ling2": "小玲",
        "xiao ling": "小玲",
        "xiao lin3": "小林",
        "xiao lin2": "小林",
        "xiao lin": "小林",
        "xiao liang3": "小梁",
        "xiao liang2": "小梁",
        "xiao liang": "小梁",
        "xiao li3": "小莉",
        "xiao li2": "小莉",
        "xiao li": "小莉",
        "xiao lan6": "小兰",
        "xiao lan5": "小蓝",
        "xiao lan4": "小兰",
        "xiao lan3": "小蓝",
        "xiao lan2": "小兰",
        "xiao lan": "小蓝",
        "xiao la3": "小拉",
        "xiao la2": "小拉",
        "xiao la": "小拉",
        "xiao ke3": "小可",
        "xiao ke2": "小可",
        "xiao ke": "小可",
        "xiao ka3": "小卡",
        "xiao ka2": "小卡",
        "xiao ka": "小卡",
        "xiao jun3": "小军",
        "xiao jun2": "小军",
        "xiao jun": "小军",
        "xiao juan3": "小娟",
        "xiao juan2": "小娟",
        "xiao juan": "小娟",
        "xiao jing3": "小静",
        "xiao jing2": "小静",
        "xiao jing": "小静",
        "xiao jing teng2": "萧敬腾",
        "xiao jing teng": "萧敬腾",
        "xiao jie3": "小姐",
        "xiao jie2": "小姐",
        "xiao jie": "小姐",
        "xiao jian3": "小建",
        "xiao jian2": "小建",
        "xiao jian": "小建",
        "xiao huo3": "小火",
        "xiao huo2": "小火",
        "xiao huo": "小火",
        "xiao hui3": "小灰",
        "xiao hui2": "小灰",
        "xiao hui": "小灰",
        "xiao huang6": "小黄",
        "xiao huang5": "小黄",
        "xiao huang4": "小黄",
        "xiao huang3": "小黄",
        "xiao huang2": "小黄",
        "xiao huang": "小黄",
        "xiao hua3": "小花",
        "xiao hua2": "小花",
        "xiao hua": "小花",
        "xiao hu3": "小虎",
        "xiao hu2": "小虎",
        "xiao hu": "小虎",
        "xiao hong3": "小红",
        "xiao hong2": "小红",
        "xiao hong": "小红",
        "xiao hei3": "小黑",
        "xiao hei2": "小黑",
        "xiao hei": "小黑",
        "xiao he3": "小河",
        "xiao he2": "小河",
        "xiao he": "小河",
        "xiao guo6": "小果",
        "xiao guo5": "小国",
        "xiao guo4": "小果",
        "xiao guo3": "小国",
        "xiao guo2": "小果",
        "xiao guo": "小国",
        "xiao gui": "小鬼",
        "xiao gu5": "小古",
        "xiao gu4": "小谷",
        "xiao gu4": "小古",
        "xiao gu3": "小谷",
        "xiao gu2": "小古",
        "xiao gu": "小谷",
        "xiao gong3": "小公",
        "xiao gong2": "小公",
        "xiao gong": "小公",
        "xiao ge3": "小哥",
        "xiao ge2": "小哥",
        "xiao ge": "小哥",
        "xiao ga3": "小嘎",
        "xiao ga2": "小嘎",
        "xiao ga": "小嘎",
        "xiao feng6": "小凤",
        "xiao feng5": "小风",
        "xiao feng4": "小凤",
        "xiao feng3": "小风",
        "xiao feng2": "小凤",
        "xiao feng": "小风",
        "xiao duo3": "小多",
        "xiao duo2": "小多",
        "xiao duo": "小多",
        "xiao dong4": "小冬",
        "xiao dong3": "小冬",
        "xiao dong": "小冬",
        "xiao di5": "小迪",
        "xiao di4": "小弟",
        "xiao di3": "小迪",
        "xiao di2": "小弟",
        "xiao di2": "小迪",
        "xiao di": "小弟",
        "xiao chun3": "小春",
        "xiao chun2": "小春",
        "xiao chun": "小春",
        "xiao chu3": "小初",
        "xiao chu2": "小初",
        "xiao chu": "小初",
        "xiao cheng4": "小成",
        "xiao cheng3": "小橙",
        "xiao cheng3": "小成",
        "xiao cheng2": "小橙",
        "xiao cheng2": "小成",
        "xiao cheng": "小橙",
        "xiao bei3": "小北",
        "xiao bei2": "小北",
        "xiao bei": "小北",
        "xiao bai3": "小白",
        "xiao bai2": "小白",
        "xiao bai": "小白",
        "xiao ba4": "小爸",
        "xiao ba3": "小爸",
        "xiao ba3": "小巴",
        "xiao ba2": "小爸",
        "xiao ba2": "小巴",
        "xiao ba": "小巴",
        "xiao an3": "小安",
        "xiao an2": "小安",
        "xiao an": "小安",
        "xiang hui ling4": "向蕙玲",
        "xiang hui ling3": "向蕙玲",
        "xiang hui ling2": "向蕙玲",
        "xiang hui ling": "向蕙玲",
        "xia dan4": "夏丹",
        "xia dan3": "夏丹",
        "xia dan2": "夏丹",
        "xia dan": "夏丹",
        "x jiu shao nian tuan": "X玖少年团",
        "x fire": "X玖少年团",
        "wubai & china blue": "伍佰 & China Blue",
        "wu zong xian4": "吴宗宪",
        "wu zong xian3": "吴宗宪",
        "wu zong xian2": "吴宗宪",
        "wu zong xian": "吴宗宪",
        "wu yue tian2": "五月天",
        "wu yue tian": "五月天",
        "wu yu fei2": "吴雨霏",
        "wu yu fei": "吴雨霏",
        "wu yin yin4": "吴莺音",
        "wu yin yin3": "吴莺音",
        "wu yin yin2": "吴莺音",
        "wu yin yin": "吴莺音",
        "wu tiao ren": "五条人",
        "wu qing feng2": "吴青峰",
        "wu qing feng": "吴青峰",
        "wu ke qun": "吴克群",
        "wu bai3": "伍佰",
        "wu bai2": "伍佰",
        "wu bai": "伍佰",
        "wu bai & china blue3": "伍佰 & China Blue",
        "wu bai & china blue2": "伍佰 & China Blue",
        "winnie hsin2": "辛晓琪",
        "winnie hsin": "辛晓琪",
        "william so2": "苏永康",
        "william so": "苏永康",
        "will pan2": "潘玮柏",
        "will pan": "潘玮柏",
        "weng li you4": "翁立友",
        "weng li you3": "翁立友",
        "weng li you2": "翁立友",
        "weng li you": "翁立友",
        "weibird": "韦礼安",
        "wei wei4": "韦唯",
        "wei wei3": "韦唯",
        "wei wei2": "韦唯",
        "wei wei": "韦唯",
        "wei ru yun2": "魏如昀",
        "wei ru yun": "魏如昀",
        "wei ru xuan2": "魏如萱",
        "wei ru xuan": "魏如萱",
        "wei li an2": "韦礼安",
        "wei li an": "韦礼安",
        "wei lan": "卫兰",
        "wei hong4": "韦弘",
        "wei hong3": "韦弘",
        "wei hong2": "韦弘",
        "wei hong": "韦弘",
        "wang zi yan3": "王紫妍",
        "wang zi yan2": "王紫妍",
        "wang zi yan": "王紫妍",
        "wang zhi lei": "王芷蕾",
        "wang yuan": "王源",
        "wang xin ling": "王心凌",
        "wang wen": "惘闻",
        "wang wan zhi2": "王菀之",
        "wang wan zhi": "王菀之",
        "wang shi xian4": "王识贤",
        "wang shi xian3": "王识贤",
        "wang shi xian2": "王识贤",
        "wang shi xian": "王识贤",
        "wang rui xia4": "王瑞霞",
        "wang rui xia3": "王瑞霞",
        "wang rui xia2": "王瑞霞",
        "wang rui xia": "王瑞霞",
        "wang lin kai": "王琳凯",
        "wang li4": "王莉",
        "wang li3": "王莉",
        "wang li2": "王莉",
        "wang li": "王莉",
        "wang jun kai": "王俊凯",
        "wang jun jie4": "王俊杰",
        "wang jun jie3": "王俊杰",
        "wang jun jie2": "王俊杰",
        "wang jun jie": "王俊杰",
        "wang jie4": "王杰",
        "wang jie3": "王杰",
        "wang jie2": "王杰",
        "wang jie": "王杰",
        "wang jian jie4": "王建杰",
        "wang jian jie3": "王建杰",
        "wang jian jie2": "王建杰",
        "wang jian jie": "王建杰",
        "wang feng3": "汪峰",
        "wang feng2": "汪峰",
        "wang feng": "汪峰",
        "wang fei2": "王菲",
        "wang fei": "王菲",
        "wan neng qing nian lv dian": "万能青年旅店",
        "wan fang4": "万芳",
        "wan fang3": "万芳",
        "wan fang2": "万芳",
        "wan fang": "万芳",
        "waa wei2": "魏如萱",
        "waa wei": "魏如萱",
        "vvae3": "许嵩",
        "vvae2": "许嵩",
        "vvae": "许嵩",
        "vivian chow2": "周慧敏",
        "vivian chow": "周慧敏",
        "vava3": "VaVa毛衍七",
        "vava2": "VaVa毛衍七",
        "vava": "VaVa毛衍七",
        "valen hsu2": "许茹芸",
        "valen hsu": "许茹芸",
        "unine": "UNINE",
        "twins2": "Twins",
        "twins": "Twins",
        "tian zhen3": "田震",
        "tian zhen2": "田震",
        "tian zhen": "田震",
        "tian fu zhen2": "田馥甄",
        "tian fu zhen": "田馥甄",
        "tia ray3": "袁娅维",
        "tia ray2": "袁娅维",
        "tia ray": "袁娅维",
        "theo zhu": "朱正廷",
        "the9": "THE9",
        "the either": "周迅",
        "the chairs": "椅子乐团",
        "the 9": "THE9",
        "tfboys": "TFBOYS",
        "tf boys": "TFBOYS",
        "teresa teng2": "邓丽君",
        "teresa teng": "邓丽君",
        "tat ming pair2": "达明一派",
        "tat ming pair": "达明一派",
        "tarcy su2": "苏慧伦",
        "tarcy su": "苏慧伦",
        "tanya": "蔡健雅",
        "tanya chua3": "蔡健雅",
        "tanya chua2": "蔡健雅",
        "tanya chua": "蔡健雅",
        "tang ni4": "唐妮",
        "tang ni3": "唐妮",
        "tang ni2": "唐妮",
        "tang ni": "唐妮",
        "tan yong lin": "谭咏麟",
        "tai zheng xiao4": "台正霄",
        "tai zheng xiao3": "台正霄",
        "tai zheng xiao2": "台正霄",
        "tai zheng xiao": "台正霄",
        "tai ji le dui": "太极乐队",
        "tai chi2": "太极乐队",
        "tai chi": "太极乐队",
        "sweet john": "甜约翰",
        "supermarket": "超级市场",
        "sunset rollercoaster": "落日飞车",
        "sun yan zi3": "孙燕姿",
        "sun yan zi2": "孙燕姿",
        "sun yan zi": "孙燕姿",
        "sun shu mei4": "孙淑媚",
        "sun shu mei3": "孙淑媚",
        "sun shu mei2": "孙淑媚",
        "sun shu mei": "孙淑媚",
        "sun sheng xi2": "孙盛希",
        "sun sheng xi": "孙盛希",
        "sun nan3": "孙楠",
        "sun nan2": "孙楠",
        "sun nan": "孙楠",
        "su yong kang2": "苏永康",
        "su yong kang": "苏永康",
        "su rui4": "苏芮",
        "su rui3": "苏芮",
        "su rui2": "苏芮",
        "su rui": "苏芮",
        "su hui lun": "苏慧伦",
        "su da lv3": "苏打绿",
        "su da lv2": "苏打绿",
        "su da lv": "苏打绿",
        "stolen": "秘密行动",
        "stephy tang2": "邓丽欣",
        "stephy tang": "邓丽欣",
        "stefanie sun3": "孙燕姿",
        "stefanie sun2": "孙燕姿",
        "stefanie sun": "孙燕姿",
        "sound fragment": "声音碎片",
        "song dongye3": "宋冬野",
        "song dongye2": "宋冬野",
        "song dongye": "宋冬野",
        "song dong ye2": "宋冬野",
        "song dong ye": "宋冬野",
        "sodagreen4": "苏打绿",
        "sodagreen3": "苏打绿",
        "sodagreen2": "苏打绿",
        "sodagreen": "苏打绿",
        "snh48": "SNH48",
        "snh48 2": "SNH48",
        "sing nv tuan": "SING女团",
        "sing female group": "SING女团",
        "show lo2": "罗志祥",
        "show lo": "罗志祥",
        "shirley kwan2": "关淑怡",
        "shirley kwan": "关淑怡",
        "shi shi2": "孙盛希",
        "shi shi": "孙盛希",
        "sheng xiang": "盛翔",
        "shen yi cheng2": "沈以诚",
        "shen yi cheng": "沈以诚",
        "shawn yue2": "余文乐",
        "shawn yue": "余文乐",
        "second hand rose": "二手玫瑰",
        "sarah chen2": "陈淑桦",
        "sarah chen": "陈淑桦",
        "sandy lam2": "林忆莲",
        "sandy lam": "林忆莲",
        "sammi cheng2": "郑秀文",
        "sammi cheng": "郑秀文",
        "sally yeh2": "叶倩文",
        "sally yeh": "叶倩文",
        "s.h.e": "S.H.E",
        "ruan ling yu4": "阮玲玉",
        "ruan ling yu3": "阮玲玉",
        "ruan ling yu2": "阮玲玉",
        "ruan ling yu": "阮玲玉",
        "roy wang": "王源",
        "ronghao li": "李荣浩",
        "rong zu er": "容祖儿",
        "rong rong4": "蓉蓉",
        "rong rong3": "蓉蓉",
        "rong rong2": "蓉蓉",
        "rong rong": "蓉蓉",
        "ronald cheng2": "郑中基",
        "ronald cheng": "郑中基",
        "roman tam2": "罗文",
        "roman tam": "罗文",
        "re-tros": "重塑雕像的权利",
        "rene liu2": "刘若英",
        "rene liu": "刘若英",
        "re yi sha": "热依莎",
        "rainie yang2": "杨丞琳",
        "rainie yang": "杨丞琳",
        "r1se2": "R1SE",
        "r1se": "R1SE",
        "quan yi4": "全怡",
        "quan yi3": "全怡",
        "quan yi2": "全怡",
        "quan yi": "全怡",
        "qiu hai zheng4": "裘海正",
        "qiu hai zheng3": "裘海正",
        "qiu hai zheng2": "裘海正",
        "qiu hai zheng": "裘海正",
        "qing feng2": "吴青峰",
        "qing feng": "吴青峰",
        "qin hao3": "秦昊",
        "qin hao2": "秦昊",
        "qin hao": "秦昊",
        "qi yu3": "齐豫",
        "qi yu2": "齐豫",
        "qi yu": "齐豫",
        "qi yi2": "祁艺",
        "qi yi": "祁艺",
        "qi qin3": "齐秦",
        "qi qin2": "齐秦",
        "qi qin": "齐秦",
        "puppiebelly": "汉堡黄",
        "pu shu3": "朴树",
        "pu shu2": "朴树",
        "pu shu": "朴树",
        "priscilla chan2": "陈慧娴",
        "priscilla chan": "陈慧娴",
        "power station2": "动力火车",
        "power station": "动力火车",
        "phil lam2": "林奕匡",
        "phil lam": "林奕匡",
        "penny tai": "戴佩妮",
        "peng li4": "澎澎",
        "peng li3": "澎澎",
        "peng li2": "澎澎",
        "peng li": "澎澎",
        "pan yue yun4": "潘越云",
        "pan yue yun3": "潘越云",
        "pan yue yun2": "潘越云",
        "pan yue yun": "潘越云",
        "pan xiu qiong4": "潘秀琼",
        "pan xiu qiong3": "潘秀琼",
        "pan xiu qiong2": "潘秀琼",
        "pan xiu qiong": "潘秀琼",
        "pan wei bo": "潘玮柏",
        "pan an bang4": "潘安邦",
        "pan an bang3": "潘安邦",
        "pan an bang2": "潘安邦",
        "pan an bang": "潘安邦",
        "pakho chau2": "周柏豪",
        "pakho chau": "周柏豪",
        "p.k.14": "P.K.14",
        "ou yang na na": "欧阳娜娜",
        "osn": "高尔宣",
        "nova heart": "Nova Heart",
        "nono4": "Nono",
        "nono3": "Nono",
        "nono2": "Nono",
        "nono": "Nono",
        "nong nong": "陈立农",
        "no party for caodong": "草东没有派对",
        "nine percent": "NINE PERCENT",
        "nicholas tse2": "谢霆锋",
        "nicholas tse": "谢霆锋",
        "next": "乐华七子",
        "nana ouyang": "欧阳娜娜",
        "nan quan ma ma2": "南拳妈妈",
        "nan quan ma ma": "南拳妈妈",
        "na ying3": "那英",
        "na ying2": "那英",
        "na ying": "那英",
        "muma": "木马乐队",
        "mrs. tortoise": "海龟先生",
        "mo wen wei": "莫文蔚",
        "miriam yeung2": "杨千嬅",
        "miriam yeung": "杨千嬅",
        "mian bao duo zhu": "面包多组",
        "mei yan fang": "梅艳芳",
        "mayday3": "五月天",
        "mayday2": "五月天",
        "mayday": "五月天",
        "may cheung2": "张德兰",
        "may cheung": "张德兰",
        "masiwei3": "马思唯",
        "masiwei2": "马思唯",
        "masiwei": "马思唯",
        "mao buyi3": "毛不易",
        "mao buyi2": "毛不易",
        "mao buyi": "毛不易",
        "mao bu yi3": "毛不易",
        "mao bu yi2": "毛不易",
        "mao bu yi": "毛不易",
        "mao a min4": "毛阿敏",
        "mao a min3": "毛阿敏",
        "mao a min2": "毛阿敏",
        "mao a min": "毛阿敏",
        "ma si wei2": "马思唯",
        "ma si wei": "马思唯",
        "ma di3": "马頔",
        "ma di2": "马頔",
        "ma di": "马頔",
        "lv fang4": "吕方",
        "lv fang3": "吕方",
        "lv fang2": "吕方",
        "lv fang": "吕方",
        "luo zhi xiang": "罗志祥",
        "luo wen2": "罗文",
        "luo wen": "罗文",
        "luo shi feng4": "罗时丰",
        "luo shi feng3": "罗时丰",
        "luo shi feng2": "罗时丰",
        "luo shi feng": "罗时丰",
        "luo fang2": "罗纺",
        "luo fang": "罗纺",
        "lu guang zhong2": "卢广仲",
        "lu guang zhong": "卢广仲",
        "lu guang zhong": "卢冠廷",
        "lu guan zhong2": "卢冠廷",
        "lu guan zhong": "卢冠廷",
        "long qian yi4": "龙千玉",
        "long qian yi3": "龙千玉",
        "long qian yi2": "龙千玉",
        "long qian yi": "龙千玉",
        "liu yun4": "刘韵",
        "liu yun3": "刘韵",
        "liu yun2": "刘韵",
        "liu yun": "刘韵",
        "liu yi fei": "刘亦菲",
        "liu xi ming4": "刘锡明",
        "liu xi ming3": "刘锡明",
        "liu xi ming2": "刘锡明",
        "liu xi ming": "刘锡明",
        "liu wen zheng4": "刘文正",
        "liu wen zheng3": "刘文正",
        "liu wen zheng2": "刘文正",
        "liu wen zheng": "刘文正",
        "liu si han3": "刘思涵",
        "liu si han2": "刘思涵",
        "liu si han": "刘思涵",
        "liu ruo ying": "刘若英",
        "liu nong4": "刘农",
        "liu nong3": "刘农",
        "liu nong2": "刘农",
        "liu nong": "刘农",
        "liu mei jun4": "刘美君",
        "liu mei jun3": "刘美君",
        "liu mei jun2": "刘美君",
        "liu mei jun": "刘美君",
        "liu jia chang4": "刘家昌",
        "liu jia chang3": "刘家昌",
        "liu jia chang2": "刘家昌",
        "liu jia chang": "刘家昌",
        "liu huan4": "刘欢",
        "liu huan3": "刘欢",
        "liu huan2": "刘欢",
        "liu huan": "刘欢",
        "liu fu zhu4": "刘福助",
        "liu fu zhu3": "刘福助",
        "liu fu zhu2": "刘福助",
        "liu fu zhu": "刘福助",
        "liu de hua3": "刘德华",
        "liu de hua2": "刘德华",
        "liu de hua": "刘德华",
        "liu bo xin2": "刘柏辛",
        "liu bo xin": "刘柏辛",
        "lisa wang2": "王芷蕾",
        "lisa wang": "王芷蕾",
        "lin zi xiang5": "林子祥",
        "lin zi xiang4": "林子祥",
        "lin zi xiang3": "林子祥",
        "lin zi xiang2": "林子祥",
        "lin zi xiang": "林子祥",
        "lin yu4": "林玉",
        "lin yu3": "林玉",
        "lin yu2": "林玉",
        "lin yu": "林玉",
        "lin you jia2": "林宥嘉",
        "lin you jia": "林宥嘉",
        "lin yi lian2": "林忆莲",
        "lin yi lian": "林忆莲",
        "lin yi kuang2": "林奕匡",
        "lin yi kuang": "林奕匡",
        "lin yi cheng4": "林义成",
        "lin yi cheng3": "林义成",
        "lin yi cheng2": "林义成",
        "lin yi cheng": "林义成",
        "lin qiang4": "林强",
        "lin qiang3": "林强",
        "lin qiang2": "林强",
        "lin qiang": "林强",
        "lin li4": "林立",
        "lin li3": "林立",
        "lin li2": "林立",
        "lin li": "林立",
        "lin li rong4": "林俐蓉",
        "lin li rong3": "林俐蓉",
        "lin li rong2": "林俐蓉",
        "lin li rong": "林俐蓉",
        "lin jun jie2": "林俊杰",
        "lin jun jie": "林俊杰",
        "lin hui ping4": "林慧萍",
        "lin hui ping3": "林慧萍",
        "lin hui ping2": "林慧萍",
        "lin hui ping": "林慧萍",
        "lin dai4": "林黛",
        "lin dai3": "林黛",
        "lin dai2": "林黛",
        "lin dai": "林黛",
        "lil ghost": "小鬼",
        "liao xiao jun4": "廖小军",
        "liao xiao jun3": "廖小军",
        "liao xiao jun2": "廖小军",
        "liao xiao jun": "廖小军",
        "liang yong qi": "梁咏琪",
        "liang jing ru4": "梁静茹",
        "liang jing ru3": "梁静茹",
        "liang jing ru2": "梁静茹",
        "liang jing ru": "梁静茹",
        "liang han wen2": "梁汉文",
        "liang han wen": "梁汉文",
        "li zi wei2": "李紫薇",
        "li zi wei": "李紫薇",
        "li zhi3": "李志",
        "li zhi2": "李志",
        "li zhi": "李志",
        "li yuchun": "李宇春",
        "li yu chun2": "李宇春",
        "li yu chun": "李宇春",
        "li yan qiu4": "李妍秋",
        "li yan qiu3": "李妍秋",
        "li yan qiu2": "李妍秋",
        "li yan qiu": "李妍秋",
        "li xing er4": "李幸倪",
        "li xing er3": "李幸倪",
        "li xing er2": "李幸倪",
        "li xing er": "李幸倪",
        "li xiang lan4": "李香兰",
        "li xiang lan3": "李香兰",
        "li xiang lan2": "李香兰",
        "li xiang lan": "李香兰",
        "li rong hao3": "李荣浩",
        "li rong hao2": "李荣浩",
        "li rong hao": "李荣浩",
        "li quan zhe": "李权哲",
        "li na4": "李娜",
        "li na3": "李娜",
        "li na2": "李娜",
        "li na": "李娜",
        "li ming2": "黎明",
        "li ming": "黎明",
        "li ming yi4": "李明依",
        "li ming yi3": "李明依",
        "li ming yi2": "李明依",
        "li ming yi": "李明依",
        "li mei feng": "李美凤",
        "li li hua": "李丽华",
        "li ke qin2": "李克勤",
        "li ke qin": "李克勤",
        "li jun4": "李珺",
        "li jun3": "李珺",
        "li jun2": "李珺",
        "li jun": "李珺",
        "li jing li4": "李静丽",
        "li jing li3": "李静丽",
        "li jing li2": "李静丽",
        "li jing li": "李静丽",
        "li jian qing4": "李剑青",
        "li jian qing3": "李剑青",
        "li jian qing2": "李剑青",
        "li jian qing": "李剑青",
        "li jian fu4": "李建复",
        "li jian fu3": "李建复",
        "li jian fu2": "李建复",
        "li jian fu": "李建复",
        "li jia yi": "李佳怡",
        "li jia wei4": "李佳薇",
        "li jia wei3": "李佳薇",
        "li jia wei2": "李佳薇",
        "li jia wei": "李佳薇",
        "li guo xiang4": "李国祥",
        "li guo xiang3": "李国祥",
        "li guo xiang2": "李国祥",
        "li guo xiang": "李国祥",
        "li gu lan4": "李谷兰",
        "li gu lan3": "李谷兰",
        "li gu lan2": "李谷兰",
        "li gu lan": "李谷兰",
        "li bi hua4": "李碧华",
        "li bi hua3": "李碧华",
        "li bi hua2": "李碧华",
        "li bi hua": "李碧华",
        "lexie liu3": "刘柏辛",
        "lexie liu2": "刘柏辛",
        "lexie liu": "刘柏辛",
        "leslie cheung2": "张国荣",
        "leslie cheung": "张国荣",
        "leon lai2": "黎明",
        "leon lai": "黎明",
        "leo ku2": "古巨基",
        "leo ku": "古巨基",
        "lei an na4": "雷安娜",
        "lei an na3": "雷安娜",
        "lei an na2": "雷安娜",
        "lei an na": "雷安娜",
        "leehom wang": "王力宏",
        "lee hom wang": "王力宏",
        "le hua qi zi": "乐华七子",
        "le di4": "乐蒂",
        "le di3": "乐蒂",
        "le di2": "乐蒂",
        "le di": "乐蒂",
        "lan yi bang4": "蓝奕邦",
        "lan yi bang3": "蓝奕邦",
        "lan yi bang2": "蓝奕邦",
        "lan yi bang": "蓝奕邦",
        "lala hsu2": "徐佳莹",
        "lala hsu": "徐佳莹",
        "kunkun": "蔡徐坤",
        "kuang mei yun": "邝美云",
        "kong ge li2": "孔格里",
        "kong ge li": "孔格里",
        "khalil fong2": "方大同",
        "khalil fong": "方大同",
        "kenji wu2": "吴克群",
        "kenji wu": "吴克群",
        "kelly yu3": "于文文",
        "kelly yu2": "于文文",
        "kelly yu": "于文文",
        "kelly chen2": "陈慧琳",
        "kelly chen": "陈慧琳",
        "kay tse2": "谢安琪",
        "kay tse": "谢安琪",
        "kary ng2": "吴雨霏",
        "kary ng": "吴雨霏",
        "karry wang": "王俊凯",
        "karen mok2": "莫文蔚",
        "karen mok": "莫文蔚",
        "kang kang4": "康康",
        "kang kang3": "康康",
        "kang kang2": "康康",
        "kang kang": "康康",
        "justin huang": "黄明昊",
        "joyside": "Joyside",
        "jony j3": "Jony J",
        "jony j2": "Jony J",
        "jony j": "Jony J",
        "jolin tsai3": "蔡依林",
        "jolin tsai2": "蔡依林",
        "jolin tsai": "蔡依林",
        "joker xue3": "薛之谦",
        "joker xue2": "薛之谦",
        "joker xue": "薛之谦",
        "joey yung2": "容祖儿",
        "joey yung": "容祖儿",
        "jj lin3": "林俊杰",
        "jj lin2": "林俊杰",
        "jj lin": "林俊杰",
        "jiu lian zhen ren": "九连真人",
        "jing ting4": "静婷",
        "jing ting3": "静婷",
        "jing ting2": "静婷",
        "jing ting": "静婷",
        "jin zhi juan4": "金智娟",
        "jin zhi juan3": "金智娟",
        "jin zhi juan2": "金智娟",
        "jin zhi juan": "金智娟",
        "jin shan4": "金山",
        "jin shan3": "金山",
        "jin shan2": "金山",
        "jin shan": "金山",
        "jiang yu heng4": "江语恒",
        "jiang yu heng3": "江语恒",
        "jiang yu heng2": "江语恒",
        "jiang yu heng": "江语恒",
        "jiang shu na4": "江淑娜",
        "jiang shu na3": "江淑娜",
        "jiang shu na2": "江淑娜",
        "jiang shu na": "江淑娜",
        "jiang hui4": "江蕙",
        "jiang hui3": "江蕙",
        "jiang hui2": "江蕙",
        "jiang hui": "江蕙",
        "jiang hong4": "江宏",
        "jiang hong3": "江宏",
        "jiang hong2": "江宏",
        "jiang hong": "江宏",
        "jiang hai jia4": "江海迦",
        "jiang hai jia3": "江海迦",
        "jiang hai jia2": "江海迦",
        "jiang hai jia": "江海迦",
        "jay chou": "周杰伦",
        "jason chan2": "陈柏宇",
        "jason chan": "陈柏宇",
        "janice vidal2": "卫兰",
        "janice vidal": "卫兰",
        "jane zhang3": "张靓颖",
        "jane zhang2": "张靓颖",
        "jane zhang": "张靓颖",
        "jam hsiao3": "萧敬腾",
        "jam hsiao2": "萧敬腾",
        "jam hsiao": "萧敬腾",
        "jacky cheung4": "张学友",
        "jacky cheung3": "张学友",
        "jacky cheung2": "张学友",
        "jacky cheung": "张学友",
        "jackson yee": "易烊千玺",
        "ivana wong2": "王菀之",
        "ivana wong": "王菀之",
        "into12": "INTO1",
        "into1": "INTO1",
        "huang ying ying4": "黄莺莺",
        "huang ying ying3": "黄莺莺",
        "huang ying ying2": "黄莺莺",
        "huang ying ying": "黄莺莺",
        "huang yi ling4": "黄乙玲",
        "huang yi ling3": "黄乙玲",
        "huang yi ling2": "黄乙玲",
        "huang yi ling": "黄乙玲",
        "huang yi da": "黄义达",
        "huang yao ming": "黄耀明",
        "huang xuan2": "黄宣",
        "huang xuan": "黄宣",
        "huang xin chun": "黄新淳",
        "huang si ting4": "黄思婷",
        "huang si ting3": "黄思婷",
        "huang si ting2": "黄思婷",
        "huang si ting": "黄思婷",
        "huang shu jun4": "黄舒骏",
        "huang shu jun3": "黄舒骏",
        "huang shu jun2": "黄舒骏",
        "huang shu jun": "黄舒骏",
        "huang ming hao": "黄明昊",
        "huang ke wei4": "黄克伟",
        "huang ke wei3": "黄克伟",
        "huang ke wei2": "黄克伟",
        "huang ke wei": "黄克伟",
        "huang kai qin4": "黄凯芹",
        "huang kai qin3": "黄凯芹",
        "huang kai qin2": "黄凯芹",
        "huang kai qin": "黄凯芹",
        "huang jia qiang2": "黄家强",
        "huang jia qiang": "黄家强",
        "huang jia ju2": "黄家驹",
        "huang jia ju": "黄家驹",
        "huang guan zhong2": "黄贯中",
        "huang guan zhong": "黄贯中",
        "huang da wei4": "黄大炜",
        "huang da wei3": "黄大炜",
        "huang da wei2": "黄大炜",
        "huang da wei": "黄大炜",
        "hua wa wa4": "华娃",
        "hua wa wa3": "华娃",
        "hua wa wa2": "华娃",
        "hua wa wa": "华娃",
        "hua chenyu3": "华晨宇",
        "hua chenyu2": "华晨宇",
        "hua chenyu": "华晨宇",
        "hua chen yu2": "华晨宇",
        "hua chen yu": "华晨宇",
        "hu yan bin4": "胡彦斌",
        "hu yan bin3": "胡彦斌",
        "hu yan bin2": "胡彦斌",
        "hu yan bin": "胡彦斌",
        "hu die4": "胡蝶",
        "hu die3": "胡蝶",
        "hu die2": "胡蝶",
        "hu die": "胡蝶",
        "hu de fu4": "胡德夫",
        "hu de fu3": "胡德夫",
        "hu de fu2": "胡德夫",
        "hu de fu": "胡德夫",
        "hong yi zhou2": "洪一舟",
        "hong yi zhou": "洪一舟",
        "hiperson": "海朋森",
        "hins cheung2": "张敬轩",
        "hins cheung": "张敬轩",
        "hedgehog": "刺猬",
        "hebe tien3": "田馥甄",
        "hebe tien2": "田馥甄",
        "hebe tien": "田馥甄",
        "he yong3": "何勇",
        "he yong2": "何勇",
        "he yong": "何勇",
        "he yi fan4": "贺一航",
        "he yi fan3": "贺一航",
        "he yi fan2": "贺一航",
        "he yi fan": "贺一航",
        "hao-mei zhang": "张惠妹",
        "hao mei": "好妹妹",
        "hao mei mei2": "好妹妹",
        "hao mei mei": "好妹妹",
        "hang on the box": "挂在盒子上",
        "han hong3": "韩红",
        "han hong2": "韩红",
        "han hong": "韩红",
        "hacken lee2": "李克勤",
        "hacken lee": "李克勤",
        "guo jing": "郭静",
        "guo fu cheng": "郭富城",
        "guo ding4": "郭顶",
        "guo ding3": "郭顶",
        "guo ding2": "郭顶",
        "guo ding": "郭顶",
        "guo cai jie2": "郭采洁",
        "guo cai jie": "郭采洁",
        "guan zheng jie4": "关正杰",
        "guan zheng jie3": "关正杰",
        "guan zheng jie2": "关正杰",
        "guan zheng jie": "关正杰",
        "guan xiao tong": "关晓彤",
        "guan shu yi": "关淑怡",
        "guan ju hua4": "关菊华",
        "guan ju hua3": "关菊华",
        "guan ju hua2": "关菊华",
        "guan ju hua": "关菊华",
        "gu ju ji2": "古巨基",
        "gu ju ji": "古巨基",
        "grasshopper2": "草蜢",
        "grasshopper": "草蜢",
        "gong qiu xia4": "龚秋霞",
        "gong qiu xia3": "龚秋霞",
        "gong qiu xia2": "龚秋霞",
        "gong qiu xia": "龚秋霞",
        "gnz48": "GNZ48",
        "gigi leung2": "梁咏琪",
        "gigi leung": "梁咏琪",
        "george lam2": "林子祥",
        "george lam": "林子祥",
        "ge lan4": "葛兰",
        "ge lan3": "葛兰",
        "ge lan2": "葛兰",
        "ge lan": "葛兰",
        "gai3": "GAI周延",
        "gai2": "GAI周延",
        "gai": "GAI周延",
        "g.e.m.4": "邓紫棋",
        "g.e.m.3": "邓紫棋",
        "g.e.m.2": "邓紫棋",
        "g.e.m.": "邓紫棋",
        "fish leong4": "梁静茹",
        "fish leong3": "梁静茹",
        "fish leong2": "梁静茹",
        "fish leong": "梁静茹",
        "fiona sit2": "薛凯琪",
        "fiona sit": "薛凯琪",
        "feng fei fei4": "凤飞飞",
        "feng fei fei3": "凤飞飞",
        "feng fei fei2": "凤飞飞",
        "feng fei fei": "凤飞飞",
        "fei yu qing4": "费玉清",
        "fei yu qing3": "费玉清",
        "fei yu qing2": "费玉清",
        "fei yu qing": "费玉清",
        "fei wang": "王菲",
        "fei er le tuan": "飞儿乐团",
        "fazi": "法兹乐队",
        "faye wong3": "王菲",
        "faye wong2": "王菲",
        "faye wong": "王菲",
        "fang wen lin4": "方文琳",
        "fang wen lin3": "方文琳",
        "fang wen lin2": "方文琳",
        "fang wen lin": "方文琳",
        "fang li shen4": "方力申",
        "fang li shen3": "方力申",
        "fang li shen2": "方力申",
        "fang li shen": "方力申",
        "fang dong de mao3": "房东的猫",
        "fang dong de mao2": "房东的猫",
        "fang dong de mao": "房东的猫",
        "fang da tong2": "方大同",
        "fang da tong": "方大同",
        "fan cheng cheng": "范丞丞",
        "faith yang2": "杨乃文",
        "faith yang": "杨乃文",
        "f.i.r.2": "飞儿乐团",
        "f.i.r.": "飞儿乐团",
        "eric chou": "周兴哲",
        "elva hsiao": "萧亚轩",
        "elephant gym": "大象体操",
        "edmond leung2": "梁汉文",
        "edmond leung": "梁汉文",
        "edison chen2": "陈冠希",
        "edison chen": "陈冠希",
        "eason chan4": "陈奕迅",
        "eason chan3": "陈奕迅",
        "eason chan2": "陈奕迅",
        "eason chan": "陈奕迅",
        "du de wei4": "杜德伟",
        "du de wei3": "杜德伟",
        "du de wei2": "杜德伟",
        "du de wei": "杜德伟",
        "dou wei3": "窦唯",
        "dou wei2": "窦唯",
        "dou wei": "窦唯",
        "dong nan": "东南",
        "dong li huo che": "动力火车",
        "ding ze ren": "丁泽仁",
        "ding dang": "丁当",
        "dilraba": "迪丽热巴",
        "dicky cheung2": "张卫健",
        "dicky cheung": "张卫健",
        "deserts chang": "张悬",
        "deng zi qi3": "邓紫棋",
        "deng zi qi2": "邓紫棋",
        "deng zi qi": "邓紫棋",
        "deng li xin2": "邓丽欣",
        "deng li xin": "邓丽欣",
        "deng li jun": "邓丽君",
        "deng jian qi2": "邓见起",
        "deng jian qi": "邓见起",
        "demo": "德莫",
        "della2": "丁当",
        "della": "丁当",
        "de mo": "德莫",
        "david tao": "陶喆",
        "danny chan2": "陈百强",
        "danny chan": "陈百强",
        "da zi3": "大紫",
        "da zi2": "大紫",
        "da zi": "大紫",
        "da zhou3": "大周",
        "da zhou2": "大周",
        "da zhou": "大周",
        "da zhong3": "大中",
        "da zhong2": "大中",
        "da zhong": "大中",
        "da zheng3": "大郑",
        "da zheng2": "大郑",
        "da zheng": "大郑",
        "da zhen3": "大珍",
        "da zhen2": "大珍",
        "da zhen": "大珍",
        "da zha3": "大扎",
        "da zha2": "大扎",
        "da zha": "大扎",
        "da ze3": "大泽",
        "da ze2": "大泽",
        "da ze": "大泽",
        "da za3": "大扎",
        "da za2": "大扎",
        "da za": "大扎",
        "da yun6": "大芸",
        "da yun5": "大云",
        "da yun4": "大芸",
        "da yun3": "大云",
        "da yun2": "大芸",
        "da yun": "大云",
        "da yong3": "大勇",
        "da yong2": "大勇",
        "da yong": "大勇",
        "da ying3": "大英",
        "da ying2": "大英",
        "da ying": "大英",
        "da ye3": "大叶",
        "da ye2": "大叶",
        "da ye": "大叶",
        "da yan3": "大燕",
        "da yan2": "大燕",
        "da yan": "大燕",
        "da ya3": "大雅",
        "da ya2": "大雅",
        "da ya": "大雅",
        "da xue3": "大雪",
        "da xue2": "大雪",
        "da xue": "大雪",
        "da xu3": "大徐",
        "da xu2": "大徐",
        "da xu": "大徐",
        "da xiu3": "大秀",
        "da xiu2": "大秀",
        "da xiu": "大秀",
        "da xiong3": "大雄",
        "da xiong2": "大雄",
        "da xiong": "大雄",
        "da xin3": "大新",
        "da xin2": "大新",
        "da xin": "大新",
        "da xia7": "大霞",
        "da xia6": "大夏",
        "da xia5": "大霞",
        "da xia4": "大夏",
        "da xia2": "大霞",
        "da xia": "大夏",
        "da xi6": "大西",
        "da xi5": "大西",
        "da xi4": "大西",
        "da xi3": "大西",
        "da xi2": "大西",
        "da xi": "大西",
        "da wu3": "大吴",
        "da wu2": "大吴",
        "da wu": "大吴",
        "da wei6": "大伟",
        "da wei5": "大伟",
        "da wei4": "大伟",
        "da wei3": "大伟",
        "da wei2": "大伟",
        "da wei": "大伟",
        "da wa3": "大瓦",
        "da wa2": "大瓦",
        "da wa": "大瓦",
        "da tu3": "大土",
        "da tu2": "大土",
        "da tu": "大土",
        "da tian3": "大田",
        "da tian2": "大田",
        "da tian": "大田",
        "da tang3": "大唐",
        "da tang2": "大唐",
        "da tang": "大唐",
        "da ta3": "大塔",
        "da ta2": "大塔",
        "da ta": "大塔",
        "da sun3": "大孙",
        "da sun2": "大孙",
        "da sun": "大孙",
        "da shui3": "大水",
        "da shui2": "大水",
        "da shui": "大水",
        "da shi3": "大石",
        "da shi2": "大石",
        "da shi": "大石",
        "da shan3": "大山",
        "da shan2": "大山",
        "da shan": "大山",
        "da sha3": "大莎",
        "da sha2": "大莎",
        "da sha": "大莎",
        "da sa3": "大萨",
        "da sa2": "大萨",
        "da sa": "大萨",
        "da re3": "大热",
        "da re2": "大热",
        "da re": "大热",
        "da qu3": "大曲",
        "da qu2": "大曲",
        "da qu": "大曲",
        "da qiu3": "大秋",
        "da qiu2": "大秋",
        "da qiu": "大秋",
        "da qing6": "大青",
        "da qing5": "大青",
        "da qing4": "大青",
        "da qing3": "大青",
        "da qing2": "大青",
        "da qing": "大青",
        "da qin3": "大琴",
        "da qin2": "大琴",
        "da qin": "大琴",
        "da po4": "大婆",
        "da po3": "大婆",
        "da po2": "大婆",
        "da ping6": "大平",
        "da ping5": "大平",
        "da ping4": "大平",
        "da ping3": "大平",
        "da ping2": "大平",
        "da ping": "大平",
        "da nuo3": "大诺",
        "da nuo2": "大诺",
        "da nuo": "大诺",
        "da ning3": "大宁",
        "da ning2": "大宁",
        "da ning": "大宁",
        "da niang3": "大娘",
        "da niang2": "大娘",
        "da niang": "大娘",
        "da nan3": "大南",
        "da nan2": "大南",
        "da nan": "大南",
        "da mu4": "大慕",
        "da mu3": "大慕",
        "da mu3": "大木",
        "da mu2": "大慕",
        "da mu2": "大木",
        "da mu": "大木",
        "da ming yi pai": "达明一派",
        "da min3": "大民",
        "da min2": "大民",
        "da min": "大民",
        "da mi3": "大米",
        "da mi2": "大米",
        "da mi": "大米",
        "da mei3": "大美",
        "da mei2": "大美",
        "da mei": "大美",
        "da mao3": "大毛",
        "da mao2": "大毛",
        "da mao": "大毛",
        "da ma4": "大妈",
        "da ma3": "大马",
        "da ma3": "大妈",
        "da ma2": "大马",
        "da ma2": "大妈",
        "da ma": "大马",
        "da lv3": "大绿",
        "da lv2": "大绿",
        "da lv": "大绿",
        "da luo3": "大罗",
        "da luo2": "大罗",
        "da luo": "大罗",
        "da lu3": "大陆",
        "da lu2": "大陆",
        "da lu": "大陆",
        "da long3": "大龙",
        "da long2": "大龙",
        "da long": "大龙",
        "da ling3": "大玲",
        "da ling2": "大玲",
        "da ling": "大玲",
        "da lin3": "大林",
        "da lin2": "大林",
        "da lin": "大林",
        "da liang3": "大梁",
        "da liang2": "大梁",
        "da liang": "大梁",
        "da li3": "大力",
        "da li2": "大力",
        "da li": "大力",
        "da lan6": "大兰",
        "da lan5": "大蓝",
        "da lan4": "大兰",
        "da lan3": "大蓝",
        "da lan2": "大兰",
        "da lan": "大蓝",
        "da la3": "大拉",
        "da la2": "大拉",
        "da la": "大拉",
        "da ke3": "大可",
        "da ke2": "大可",
        "da ke": "大可",
        "da ka3": "大卡",
        "da ka2": "大卡",
        "da ka": "大卡",
        "da jun3": "大军",
        "da jun2": "大军",
        "da jun": "大军",
        "da juan3": "大娟",
        "da juan2": "大娟",
        "da juan": "大娟",
        "da jing3": "大静",
        "da jing2": "大静",
        "da jing": "大静",
        "da jie3": "大姐",
        "da jie2": "大姐",
        "da jie": "大姐",
        "da jian3": "大建",
        "da jian2": "大建",
        "da jian": "大建",
        "da huo3": "大火",
        "da huo2": "大火",
        "da huo": "大火",
        "da hui3": "大灰",
        "da hui2": "大灰",
        "da hui": "大灰",
        "da huang6": "大黄",
        "da huang5": "大黄",
        "da huang4": "大黄",
        "da huang3": "大黄",
        "da huang2": "大黄",
        "da huang": "大黄",
        "da hua3": "大花",
        "da hua2": "大花",
        "da hua": "大花",
        "da hu3": "大虎",
        "da hu2": "大虎",
        "da hu": "大虎",
        "da hong3": "大红",
        "da hong2": "大红",
        "da hong": "大红",
        "da hei3": "大黑",
        "da hei2": "大黑",
        "da hei": "大黑",
        "da he4": "大河",
        "da he3": "大河",
        "da he2": "大河",
        "da guo6": "大果",
        "da guo5": "大国",
        "da guo4": "大果",
        "da guo3": "大国",
        "da guo2": "大果",
        "da guo": "大国",
        "da gu3": "大古",
        "da gu2": "大古",
        "da gu": "大古",
        "da gong3": "大公",
        "da gong2": "大公",
        "da gong": "大公",
        "da ge3": "大哥",
                  "da ge2": "大哥",
                            "da ge": "大哥",
                                     "da ga3": "大嘎",
    "da ga2": "大嘎",
    "da ga": "大嘎",
    "da feng6": "大风",
    "da feng5": "大风",
    "da feng4": "大风",
    "da feng3": "大风",
    "da feng2": "大风",
    "da feng": "大风",
    "da duo3": "大多",
    "da duo2": "大多",
    "da duo": "大多",
    "da dong4": "大冬",
    "da dong3": "大冬",
    "da dong2": "大冬",
    "da di4": "大迪",
    "da di3": "大帝",
    "da di3": "大迪",
    "da di2": "大帝",
    "da di2": "大迪",
    "da di": "大帝",
    "da da yue dui": "达达乐队",
    "da chun3": "大春",
    "da chun2": "大春",
    "da chun": "大春",
    "da chu3": "大初",
    "da chu2": "大初",
    "da chu": "大初",
    "da cheng5": "大成",
    "da cheng4": "大橙",
    "da cheng4": "大成",
    "da cheng3": "大橙",
    "da cheng2": "大成",
    "da cheng": "大橙",
    "da bei3": "大北",
    "da bei2": "大北",
    "da bei": "大北",
    "da bai3": "大白",
    "da bai2": "大白",
    "da bai": "大白",
    "da ba4": "大爸",
    "da ba3": "大爸",
    "da ba3": "大巴",
    "da ba2": "大爸",
    "da ba2": "大巴",
    "da ba": "大巴",
    "da an3": "大安",
    "da an2": "大安",
    "da an": "大安",
    "cyndi wang2": "王心凌",
    "cyndi wang": "王心凌",
    "cui ping4": "崔萍",
    "cui ping3": "崔萍",
    "cui ping2": "崔萍",
    "cui ping": "崔萍",
    "cui jian": "崔健",
    "crystal liu": "刘亦菲",
    "crowd lu2": "卢广仲",
    "crowd lu": "卢广仲",
    "color girls": "Color Girls",
    "claire kuo2": "郭静",
    "claire kuo": "郭静",
    "chyi yu": "齐秦",
    "chyi chin": "齐豫",
    "chris lee3": "李宇春",
    "chris lee2": "李宇春",
    "chris lee": "李宇春",
    "chinese football": "Chinese Football",
    "cheng wei2": "程伟",
    "cheng wei": "程伟",
    "cheng lin4": "程琳",
    "cheng lin3": "程琳",
    "cheng lin2": "程琳",
    "cheng lin": "程琳",
    "cheng fang yuan2": "成方圆",
    "cheng fang yuan": "成方圆",
    "cheng fang yu yuan": "成方圆",
    "chen yi4": "陈一",
    "chen yi3": "陈一",
    "chen yi2": "陈一",
    "chen yi": "陈一",
    "chen yi xun3": "陈奕迅",
    "chen yi xun2": "陈奕迅",
    "chen yi xun": "陈奕迅",
    "chen xiao yun4": "陈小云",
    "chen xiao yun3": "陈小云",
    "chen xiao yun2": "陈小云",
    "chen xiao yun": "陈小云",
    "chen xiao dong4": "陈晓东",
    "chen xiao dong3": "陈晓东",
    "chen xiao dong2": "陈晓东",
    "chen xiao dong": "陈晓东",
    "chen wei4": "陈伟",
    "chen wei3": "陈伟",
    "chen wei2": "陈伟",
    "chen wei": "陈伟",
    "chen si an4": "陈思安",
    "chen si an3": "陈思安",
    "chen si an2": "陈思安",
    "chen si an": "陈思安",
    "chen shu hua": "陈淑桦",
    "chen sheng4": "陈升",
    "chen sheng3": "陈升",
    "chen sheng2": "陈升",
    "chen sheng": "陈升",
    "chen mei feng4": "陈美凤",
    "chen mei feng3": "陈美凤",
    "chen mei feng2": "陈美凤",
    "chen mei feng": "陈美凤",
    "chen li3": "陈粒",
    "chen li2": "陈粒",
    "chen li": "陈粒",
    "chen li nong": "陈立农",
    "chen lei4": "陈雷",
    "chen lei3": "陈雷",
    "chen lei2": "陈雷",
    "chen lei": "陈雷",
    "chen juan juan4": "陈娟娟",
    "chen juan juan3": "陈娟娟",
    "chen juan juan2": "陈娟娟",
    "chen juan juan": "陈娟娟",
    "chen jie li4": "陈洁丽",
    "chen jie li3": "陈洁丽",
    "chen jie li2": "陈洁丽",
    "chen jie li": "陈洁丽",
    "chen jian nian4": "陈建年",
    "chen jian nian3": "陈建年",
    "chen jian nian2": "陈建年",
    "chen jian nian": "陈建年",
    "chen hui yu3": "陈慧宇",
    "chen hui yu2": "陈慧宇",
    "chen hui yu": "陈慧宇",
    "chen hui xian5": "陈慧娴",
    "chen hui xian4": "陈慧娴",
    "chen hui xian3": "陈慧娴",
    "chen hui xian2": "陈慧娴",
    "chen hui xian": "陈慧娴",
    "chen hui lin": "陈慧琳",
    "chen hongyu3": "陈鸿宇",
    "chen hongyu2": "陈鸿宇",
    "chen hongyu": "陈鸿宇",
    "chen hong yu2": "陈鸿宇",
    "chen hong yu": "陈鸿宇",
    "chen guan xi": "陈冠希",
    "chen bing xu4": "陈丙须",
    "chen bing xu3": "陈丙须",
    "chen bing xu2": "陈丙须",
    "chen bing xu": "陈丙须",
    "chen bai yu2": "陈柏宇",
    "chen bai yu": "陈柏宇",
    "chen bai qiang2": "陈百强",
    "chen bai qiang": "陈百强",
    "cheer chen": "陈绮贞",
    "charlie zhou3": "周深",
    "charlie zhou2": "周深",
    "charlie zhou": "周深",
    "cgt48": "CGT48",
    "carsick cars": "Carsick Cars",
    "cao meng": "草蜢",
    "cally kwong2": "邝美云",
    "cally kwong": "邝美云",
    "cai yi lin2": "蔡依林",
    "cai yi lin": "蔡依林",
    "cai yi dong4": "蔡义东",
    "cai yi dong3": "蔡义东",
    "cai yi dong2": "蔡义东",
    "cai yi dong": "蔡义东",
    "cai xu kun": "蔡徐坤",
    "cai xing juan4": "蔡幸娟",
    "cai xing juan3": "蔡幸娟",
    "cai xing juan2": "蔡幸娟",
    "cai xing juan": "蔡幸娟",
    "cai wei ze2": "蔡维泽",
    "cai wei ze": "蔡维泽",
    "cai qiu feng4": "蔡秋凤",
    "cai qiu feng3": "蔡秋凤",
    "cai qiu feng2": "蔡秋凤",
    "cai qiu feng": "蔡秋凤",
    "cai qin4": "蔡琴",
    "cai qin3": "蔡琴",
    "cai qin2": "蔡琴",
    "cai qin": "蔡琴",
    "cai ling4": "蔡龄",
    "cai ling3": "蔡龄",
    "cai ling2": "蔡龄",
    "cai ling": "蔡龄",
    "cai jian ya2": "蔡健雅",
    "cai jian ya": "蔡健雅",
    "cai guo quan4": "蔡国权",
    "cai guo quan3": "蔡国权",
    "cai guo quan2": "蔡国权",
    "cai guo quan": "蔡国权",
    "cai guo qing4": "蔡国庆",
    "cai guo qing3": "蔡国庆",
    "cai guo qing2": "蔡国庆",
    "cai guo qing": "蔡国庆",
    "buyi band": "布衣乐队",
    "bu shi ya": "布施雅",
    "brainfailure": "脑浊",
    "bonbon girls 303": "硬糖少女303",
    "bluev": "BlueV",
    "bii2": "毕书尽",
    "bii": "毕书尽",
    "bi wen jun": "毕雯珺",
    "bi shu jin": "毕书尽",
    "beyond2": "Beyond",
    "beyond": "Beyond",
    "bej48": "BEJ48",
    "bai hua lin": "白桦林",
    "bai guang4": "白光",
    "bai guang3": "白光",
    "bai guang2": "白光",
    "bai guang": "白光",
    "bai bing bing4": "白冰冰",
    "bai bing bing3": "白冰冰",
    "bai bing bing2": "白冰冰",
    "bai bing bing": "白冰冰",
    "azora chin": "尤长靖",
    "anthony wong2": "黄耀明",
    "anthony wong": "黄耀明",
    "anita mui2": "梅艳芳",
    "anita mui": "梅艳芳",
    "angela zhang": "张韶涵",
    "andy lau4": "刘德华",
    "andy lau3": "刘德华",
    "andy lau2": "刘德华",
    "andy lau": "刘德华",
    "andy hui2": "许志安",
    "andy hui": "许志安",
    "a-mei": "张惠妹",
    "amber kuo": "郭采洁",
    "amanda lee2": "李美凤",
    "amanda lee": "李美凤",
    "a-lin": "黄丽玲",
    "alan tam2": "谭咏麟",
    "alan tam": "谭咏麟",
    "akb48 china": "AKB48 China",
    "adam fan": "范丞丞",
    "accusefive": "告五人",
    "aaron kwok2": "郭富城",
    "aaron kwok": "郭富城",
    "a zhou4": "阿周",
    "a zhou3": "阿周",
    "a zhou2": "阿周",
    "a zhou": "阿周",
    "a zhong4": "阿中",
    "a zhong3": "阿中",
    "a zhong2": "阿中",
    "a zhong": "阿中",
    "a zheng8": "阿郑",
    "a zheng7": "阿正",
    "a zheng6": "阿郑",
    "a zheng5": "阿正",
    "a zheng4": "阿郑",
    "a zheng3": "阿正",
    "a zheng2": "阿郑",
    "a zheng": "阿郑",
    "a zheng": "阿正",
    "a zhen4": "阿珍",
    "a zhen3": "阿珍",
    "a zhen2": "阿珍",
    "a zhen": "阿珍",
    "a zha4": "阿扎",
    "a zha3": "阿扎",
    "a zha2": "阿扎",
    "a zha": "阿扎",
    "a ze4": "阿泽",
    "a ze3": "阿泽",
    "a ze2": "阿泽",
    "a ze": "阿泽",
    "a za4": "阿扎",
    "a za3": "阿扎",
    "a za2": "阿扎",
    "a za": "阿扎",
    "a yun4": "阿芸",
    "a yun3": "阿芸",
    "a yun2": "阿芸",
    "a yun": "阿芸",
    "a yun a3": "阿云阿",
    "a yun a2": "阿云阿",
    "a yun a": "阿云阿",
    "a yong4": "阿勇",
    "a yong3": "阿勇",
    "a yong2": "阿勇",
    "a yong": "阿勇",
    "a ying4": "阿英",
    "a ying3": "阿英",
    "a ying2": "阿英",
    "a ying": "阿英",
    "a ye4": "阿叶",
    "a ye3": "阿叶",
    "a ye2": "阿叶",
    "a ye": "阿叶",
    "a yang4": "阿洋",
    "a yang3": "阿洋",
    "a yang2": "阿洋",
    "a yang": "阿洋",
    "a yan4": "阿燕",
    "a yan3": "阿燕",
    "a yan2": "阿燕",
    "a yan": "阿燕",
    "a ya4": "阿雅",
    "a ya3": "阿雅",
    "a ya2": "阿雅",
    "a ya": "阿雅",
    "a xue4": "阿雪",
    "a xue3": "阿雪",
    "a xue2": "阿雪",
    "a xue": "阿雪",
    "a xu8": "阿徐",
    "a xu7": "阿旭",
    "a xu6": "阿徐",
    "a xu5": "阿旭",
    "a xu4": "阿徐",
    "a xu3": "阿旭",
    "a xu2": "阿徐",
    "a xu": "阿旭",
    "a xu": "阿徐",
    "a xiu4": "阿秀",
    "a xiu3": "阿秀",
    "a xiu2": "阿秀",
    "a xiu": "阿秀",
    "a xiong4": "阿雄",
    "a xiong3": "阿雄",
    "a xiong2": "阿雄",
    "a xiong": "阿雄",
    "a xin4": "阿信",
    "a xin3": "阿信",
    "a xin2": "阿信",
    "a xin": "阿信",
    "a xiang4": "阿祥",
    "a xiang3": "阿祥",
    "a xiang2": "阿祥",
    "a xiang": "阿祥",
    "a xia4": "阿霞",
    "a xia3": "阿霞",
    "a xia2": "阿霞",
    "a xia": "阿霞",
    "a xi4": "阿西",
    "a xi3": "阿西",
    "a xi2": "阿西",
    "a xi": "阿西",
    "a wu4": "阿吴",
    "a wu3": "阿吴",
    "a wu2": "阿吴",
    "a wu": "阿吴",
    "a wei8": "阿威",
    "a wei7": "阿伟",
    "a wei6": "阿威",
    "a wei5": "阿伟",
    "a wei4": "阿威",
    "a wei3": "阿伟",
    "a wei2": "阿威",
    "a wei": "阿伟",
    "a wei": "阿威",
    "a wa4": "阿瓦",
    "a wa3": "阿瓦",
    "a wa2": "阿瓦",
    "a wa": "阿瓦",
    "a tu4": "阿土",
    "a tu3": "阿土",
    "a tu2": "阿土",
    "a tu": "阿土",
    "a tian4": "阿田",
    "a tian3": "阿田",
    "a tian2": "阿田",
    "a tian": "阿田",
    "a tao4": "阿涛",
    "a tao3": "阿涛",
    "a tao2": "阿涛",
    "a tao": "阿涛",
    "a tang4": "阿唐",
    "a tang3": "阿唐",
    "a tang2": "阿唐",
    "a tang": "阿唐",
    "a ta4": "阿塔",
    "a ta3": "阿塔",
    "a ta2": "阿塔",
    "a ta": "阿塔",
    "a sun4": "阿孙",
    "a sun3": "阿孙",
    "a sun2": "阿孙",
    "a sun": "阿孙",
    "a shun4": "阿顺",
    "a shun3": "阿顺",
    "a shun2": "阿顺",
    "a shun": "阿顺",
    "a shui4": "阿水",
    "a shui3": "阿水",
    "a shui2": "阿水",
    "a shui": "阿水",
    "a shi4": "阿石",
    "a shi3": "阿石",
    "a shi2": "阿石",
    "a shi": "阿石",
    "a shan4": "阿山",
    "a shan3": "阿山",
    "a shan2": "阿山",
    "a shan": "阿山",
    "a sha4": "阿莎",
    "a sha3": "阿莎",
    "a sha2": "阿莎",
    "a sha": "阿莎",
    "a sen4": "阿森",
    "a sen3": "阿森",
    "a sen2": "阿森",
    "a sen": "阿森",
    "a sa4": "阿萨",
    "a sa3": "阿萨",
    "a sa2": "阿萨",
    "a sa": "阿萨",
    "a re4": "阿热",
    "a re3": "阿热",
    "a re2": "阿热",
    "a re": "阿热",
    "a quan4": "阿泉",
    "a quan3": "阿泉",
    "a quan2": "阿泉",
    "a quan": "阿泉",
    "a qu4": "阿曲",
    "a qu3": "阿曲",
    "a qu2": "阿曲",
    "a qu": "阿曲",
    "a qing4": "阿青",
    "a qing3": "阿青",
    "a qing2": "阿青",
    "a qing": "阿青",
    "a qin4": "阿琴",
    "a qin3": "阿琴",
    "a qin2": "阿琴",
    "a qin": "阿琴",
    "a qiang4": "阿强",
    "a qiang3": "阿强",
    "a qiang2": "阿强",
    "a qiang": "阿强",
    "a po4": "阿婆",
    "a po3": "阿婆",
    "a po2": "阿婆",
    "a po": "阿婆",
    "a ping8": "阿萍",
    "a ping7": "阿平",
    "a ping6": "阿萍",
    "a ping5": "阿平",
    "a ping4": "阿萍",
    "a ping3": "阿平",
    "a ping2": "阿萍",
    "a ping": "阿萍",
    "a ping": "阿平",
    "a nuo4": "阿诺",
    "a nuo3": "阿诺",
    "a nuo2": "阿诺",
    "a nuo": "阿诺",
    "a niu4": "阿牛",
    "a niu3": "阿牛",
    "a niu2": "阿牛",
    "a niu": "阿牛",
    "a ning4": "阿宁",
    "a ning3": "阿宁",
    "a ning2": "阿宁",
    "a ning": "阿宁",
    "a niang4": "阿娘",
    "a niang3": "阿娘",
    "a niang2": "阿娘",
    "a niang": "阿娘",
    "a nan4": "阿南",
    "a nan3": "阿南",
    "a nan2": "阿南",
    "a nan": "阿南",
    "a mu8": "阿慕",
    "a mu7": "阿木",
    "a mu6": "阿慕",
    "a mu5": "阿木",
    "a mu4": "阿慕",
    "a mu3": "阿木",
    "a mu2": "阿慕",
    "a mu": "阿慕",
    "a mu": "阿木",
    "a ming4": "阿明",
    "a ming3": "阿明",
    "a ming2": "阿明",
    "a ming": "阿明",
    "a min4": "阿民",
    "a min3": "阿民",
    "a min2": "阿民",
    "a min": "阿民",
    "a mi4": "阿米",
    "a mi3": "阿米",
    "a mi2": "阿米",
    "a mi": "阿米",
    "a mei9": "阿美",
    "a mei8": "阿妹",
    "a mei7": "阿妹",
    "a mei6": "阿美",
    "a mei5": "阿妹",
    "a mei4": "阿妹",
    "a mei3": "阿妹",
    "a mei3": "阿美",
    "a mei2": "阿妹",
    "a mei11": "阿妹",
    "a mei10": "阿妹",
    "a mei": "阿妹",
    "a mei": "阿美",
    "a ma8": "阿嬷",
    "a ma7": "阿马",
    "a ma6": "阿嬷",
    "a ma5": "阿马",
    "a ma4": "阿嬷",
    "a ma3": "阿马",
    "a ma2": "阿嬷",
    "a ma": "阿嬷",
    "a ma": "阿马",
    "a luo4": "阿罗",
    "a luo3": "阿罗",
    "a luo2": "阿罗",
    "a luo": "阿罗",
    "a lu4": "阿鲁",
    "a lu3": "阿鲁",
    "a lu2": "阿鲁",
    "a lu": "阿鲁",
    "a long4": "阿龙",
    "a long3": "阿龙",
    "a long2": "阿龙",
    "a long": "阿龙",
    "a ling4": "阿玲",
    "a ling3": "阿玲",
    "a ling2": "阿玲",
    "a ling": "阿玲",
    "a lin8": "阿林",
    "a lin7": "阿林",
    "a lin6": "阿林",
    "a lin5": "阿林",
    "a lin4": "阿林",
    "a lin3": "阿林",
    "a lin2": "阿林",
    "a lin": "阿林",
    "a liang4": "阿梁",
    "a liang3": "阿梁",
    "a liang2": "阿梁",
    "a liang": "阿梁",
    "a li8": "阿莉",
    "a li7": "阿丽",
    "a li6": "阿莉",
    "a li5": "阿丽",
    "a li4": "阿莉",
    "a li3": "阿丽",
    "a li2": "阿莉",
    "a li": "阿莉",
    "a li": "阿丽",
    "a lei4": "阿磊",
    "a lei3": "阿磊",
    "a lei2": "阿磊",
    "a lei": "阿磊",
    "a lan4": "阿兰",
    "a lan3": "阿兰",
    "a lan2": "阿兰",
    "a lan": "阿兰",
    "a la4": "阿拉",
    "a la3": "阿拉",
    "a la2": "阿拉",
    "a la": "阿拉",
    "a kun4": "阿坤",
    "a kun3": "阿坤",
    "a kun2": "阿坤",
    "a kun": "阿坤",
    "a ke4": "阿可",
    "a ke3": "阿可",
    "a ke2": "阿可",
    "a ke": "阿可",
    "a kang4": "阿康",
    "a kang3": "阿康",
    "a kang2": "阿康",
    "a kang": "阿康",
    "a ka4": "阿卡",
    "a ka3": "阿卡",
    "a ka2": "阿卡",
    "a ka": "阿卡",
    "a jun8": "阿钧",
    "a jun7": "阿军",
    "a jun6": "阿钧",
    "a jun5": "阿军",
    "a jun4": "阿钧",
    "a jun3": "阿军",
    "a jun2": "阿钧",
    "a jun": "阿钧",
    "a jun": "阿军",
    "a juan4": "阿娟",
    "a juan3": "阿娟",
    "a juan2": "阿娟",
    "a juan": "阿娟",
    "a jing4": "阿静",
    "a jing3": "阿静",
    "a jing2": "阿静",
    "a jing": "阿静",
    "a jie8": "阿姐",
    "a jie7": "阿杰",
    "a jie6": "阿姐",
    "a jie5": "阿杰",
    "a jie4": "阿姐",
    "a jie3": "阿杰",
    "a jie2": "阿姐",
    "a jie": "阿姐",
    "a jie": "阿杰",
    "a jiang4": "阿江",
    "a jiang3": "阿江",
    "a jiang2": "阿江",
    "a jiang": "阿江",
    "a jian4": "阿建",
    "a jian3": "阿建",
    "a jian2": "阿建",
    "a jian": "阿建",
    "a huo4": "阿火",
    "a huo3": "阿火",
    "a huo2": "阿火",
    "a huo": "阿火",
    "a huang4": "阿黄",
    "a huang3": "阿黄",
    "a huang2": "阿黄",
    "a huang": "阿黄",
    "a hua8": "阿花",
    "a hua7": "阿华",
    "a hua6": "阿花",
    "a hua5": "阿华",
    "a hua4": "阿花",
    "a hua3": "阿华",
    "a hua2": "阿花",
    "a hua": "阿华",
    "a hua": "阿花",
    "a hu4": "阿虎",
    "a hu3": "阿虎",
    "a hu2": "阿虎",
    "a hu": "阿虎",
    "a hong4": "阿红",
    "a hong3": "阿红",
    "a hong2": "阿红",
    "a hong": "阿红",
    "a he4": "阿赫",
    "a he3": "阿赫",
    "a he2": "阿赫",
    "a he": "阿赫",
    "a hao4": "阿豪",
    "a hao3": "阿豪",
    "a hao2": "阿豪",
    "a hao": "阿豪",
    "a hai4": "阿海",
    "a hai3": "阿海",
    "a hai2": "阿海",
    "a hai": "阿海",
    "a guo8": "阿果",
    "a guo7": "阿国",
    "a guo6": "阿果",
    "a guo5": "阿国",
    "a guo4": "阿果",
    "a guo3": "阿国",
    "a guo2": "阿果",
    "a guo": "阿果",
    "a guo": "阿国",
    "a gu4": "阿古",
    "a gu3": "阿古",
    "a gu2": "阿古",
    "a gu": "阿古",
    "a gong4": "阿公",
    "a gong3": "阿公",
    "a gong2": "阿公",
    "a gong": "阿公",
    "a ge4": "阿哥",
    "a ge3": "阿哥",
    "a ge2": "阿哥",
    "a ge": "阿哥",
    "a ga4": "阿嘎",
    "a ga3": "阿嘎",
    "a ga2": "阿嘎",
    "a ga": "阿嘎",
    "a feng4": "阿凤",
    "a feng3": "阿凤",
    "a feng2": "阿凤",
    "a feng": "阿凤",
    "a fang4": "阿芳",
    "a fang3": "阿芳",
    "a fang2": "阿芳",
    "a fang": "阿芳",
    "a duo4": "阿多",
    "a duo3": "阿多",
    "a duo2": "阿多",
    "a duo": "阿多",
    "a dong4": "阿东",
    "a dong3": "阿东",
    "a dong2": "阿东",
    "a dong": "阿东",
    "a di9": "阿弟",
    "a di8": "阿迪",
    "a di7": "阿弟",
    "a di6": "阿弟",
    "a di5": "阿迪",
    "a di4": "阿弟",
    "a di3": "阿弟",
             "a di2": "阿迪",
    "a di12": "阿弟",
    "a di11": "阿迪",
    "a di10": "阿弟",
    "a di": "阿弟",
    "a di": "阿弟",
            "a di": "阿迪",
    "a chu4": "阿初",
    "a chu3": "阿初",
    "a chu2": "阿初",
    "a chu": "阿初",
    "a cheng4": "阿成",
    "a cheng3": "阿成",
    "a cheng2": "阿成",
    "a cheng": "阿成",
    "a cai4": "阿蔡",
    "a cai3": "阿蔡",
    "a cai2": "阿蔡",
    "a cai": "阿蔡",
    "a bin4": "阿彬",
    "a bin3": "阿彬",
    "a bin2": "阿彬",
    "a bin": "阿彬",
    "a biao4": "阿标",
    "a biao3": "阿标",
    "a biao2": "阿标",
    "a biao": "阿标",
    "a bei4": "阿北",
    "a bei3": "阿北",
    "a bei2": "阿北",
    "a bei": "阿北",
    "a bao4": "阿宝",
    "a bao3": "阿宝",
    "a bao2": "阿宝",
    "a bao": "阿宝",
    "a ba8": "阿爸",
    "a ba7": "阿巴",
    "a ba6": "阿爸",
    "a ba5": "阿巴",
    "a ba4": "阿爸",
    "a ba3": "阿巴",
    "a ba2": "阿爸",
    "a ba": "阿爸",
    "a ba": "阿巴",
    "a an4": "阿安",
    "a an3": "阿安",
    "a an2": "阿安",
    "a an": "阿安",
    "7senses": "7SENSES"
    }
    a = {
        # === Mainland Indie & Rock ===
        "da da yue dui": "达达乐队",
        "wu tiao ren": "五条人",
        "wan neng qing nian lu dian": "万能青年旅店",
        "xin ku zi": "新裤子",
        "New Pants": "新裤子",
        "yao band": "腰乐队",
        "cui jian": "崔健",
        "puppiebelly": "汉堡黄",
        "wang wen": "惘闻",
        "buyi band": "布衣乐队",
        "second hand rose": "二手玫瑰",
        "hedgehog": "刺猬",
        "muma": "木马乐队",
        "carsick cars": "Carsick Cars",
        "chinese football": "Chinese Football",
        "re-tros": "重塑雕像的权利",
        "re-tro": "重塑雕像的权利",
        "p.k.14": "P.K.14",
        "nova heart": "Nova Heart",
        "mrs. tortoise": "海龟先生",
        "mr. tortoise": "海龟先生",
        "sound fragment": "声音碎片",
        "brainfailure": "脑浊",
        "joyside": "Joyside",
        "hang on the box": "挂在盒子上",
        "supermarket": "超级市场",
        "jiu lian zhen ren": "九连真人",
        "fa zi": "法兹乐队",
        "fazi": "法兹乐队",
        "hiperson": "海朋森",
        "stolen": "秘密行动",

        # === Mainland Pop, Folk & Rap ===
        "faye wong": "王菲",
        "ronghao li": "李荣浩",
        "hua chenyu": "华晨宇",
        "joker xue": "薛之谦",
        "vvae": "许嵩",
        "lexie liu": "刘柏辛",
        "masiwei": "马思唯",
        "vava": "VaVa毛衍七",
        "gai": "GAI周延",
        "jony j": "Jony J",
        "tia ray": "袁娅维",
        "kelly yu": "于文文",
        "jane zhang": "张靓颖",
        "pu shu": "朴树",
        "zheng jun": "郑钧",
        "dou wei": "窦唯",
        "zhang chu": "张楚",
        "he yong": "何勇",
        "xu wei": "许巍",
        "wang feng": "汪峰",
        "li zhi": "李志",
        "song dongye": "宋冬野",
        "ma di": "马頔",
        "zhao lei": "赵雷",
        "chen hongyu": "陈鸿宇",
        "fang dong de mao": "房东的猫",
        "qi qin": "齐秦",
        "qi yu": "齐豫",
        "na ying": "那英",
        "han hong": "韩红",
        "sun nan": "孙楠",
        "tian zhen": "田震",
        "mao buyi": "毛不易",
        "zhou shen": "周深",
        "charlie zhou": "周深",
        "li yuchun": "李宇春",
        "chris lee": "李宇春",

        # === Taiwanese Indie, Pop & Legends ===
        "jay chou": "周杰伦",
        "jolin tsai": "蔡依林",
        "stefanie sun": "孙燕姿",
        "mayday": "五月天",
        "hebe tien": "田馥甄",
        "yoga lin": "林宥嘉",
        "jam hsiao": "萧敬腾",
        "a-lin": "黄丽玲",
        "tanya chua": "蔡健雅",
        "penny tai": "戴佩妮",
        "cheer chen": "陈绮贞",
        "deserts chang": "张悬",
        "wubai & china blue": "伍佰 & China Blue",
        "wu bai": "伍佰",
        "no party for caodong": "草东没有派对",
        "sunset rollercoaster": "落日飞车",
        "accusefive": "告五人",
        "elephant gym": "大象体操",
        "sweet john": "甜约翰",
        "the chairs": "椅子乐团",
        "weibird": "韦礼安",
        "eric chou": "周兴哲",
        "osn": "高尔宣",
        "a-mei": "张惠妹",
        "amit": "张惠妹",
        "elva hsiao": "萧亚轩",
        "cyndi wang": "王心凌",
        "angela zhang": "张韶涵",
        "angela chang": "张韶涵",
        "rainie yang": "杨丞琳",
        "s.h.e": "S.H.E",
        "s.h.e.": "S.H.E",
        "selina jen": "任家萱",
        "ella chen": "陈嘉桦",
        "a-do": "阿杜",
        "jj lin": "林俊杰",
        "leehom wang": "王力宏",
        "wang leehom": "王力宏",
        "david tao": "陶喆",
        "show lo": "罗志祥",
        "will pan": "潘玮柏",
        "kenji wu": "吴克群",
        "f.i.r.": "飞儿乐团",
        "f.i.r": "飞儿乐团",
        "nan quan ma ma": "南拳妈妈",
        "sodagreen": "苏打绿",
        "crowd lu": "卢广仲",
        "rene liu": "刘若英",
        "karen mok": "莫文蔚",
        "fish leong": "梁静茹",
        "valen hsu": "许茹芸",
        "tarcy su": "苏慧伦",
        "faith yang": "杨乃文",
        "winnie hsin": "辛晓琪",
        "della": "丁当",
        "bii": "毕书尽",
        "yida huang": "黄义达",
        "claire kuo": "郭静",
        "power station": "动力火车",

        # === HK Cantopop & Legends ===
        "g.e.m.": "邓紫棋",
        "gem": "邓紫棋",
        "eason chan": "陈奕迅",
        "jacky cheung": "张学友",
        "andy lau": "刘德华",
        "leslie cheung": "张国荣",
        "anita mui": "梅艳芳",
        "sandy lam": "林忆莲",
        "hins cheung": "张敬轩",
        "miriam yeung": "杨千嬅",
        "joey yung": "容祖儿",
        "khalil fong": "方大同",
        "beyond": "Beyond",
        "shirley kwan": "关淑怡",
        "priscilla chan": "陈慧娴",
        "vivian chow": "周慧敏",
        "sammi cheng": "郑秀文",
        "kelly chen": "陈慧琳",
        "gigi leung": "梁咏琪",
        "charlene choi": "蔡卓妍",
        "gillian chung": "钟欣潼",
        "twins": "Twins",
        "fiona sit": "薛凯琪",
        "stephy tang": "邓丽欣",
        "kary ng": "吴雨霏",
        "janice vidal": "卫兰",
        "kay tse": "谢安琪",
        "ivana wong": "王菀之",
        "andy hui": "许志安",
        "edmond leung": "梁汉文",
        "william so": "苏永康",
        "dicky cheung": "张卫健",
        "leo ku": "古巨基",
        "hacken lee": "李克勤",
        "aaron kwok": "郭富城",
        "leon lai": "黎明",
        "nicholas tse": "谢霆锋",
        "edison chen": "陈冠希",
        "shawn yue": "余文乐",
        "pakho chau": "周柏豪",
        "jason chan": "陈柏宇",
        "phil lam": "林奕匡",
        "ronald cheng": "郑中基",
        "anthony wong": "黄耀明",
        "tat ming pair": "达明一派",
        "grasshopper": "草蜢",
        "tai chi": "太极乐队",
        "alan tam": "谭咏麟",
        "george lam": "林子祥",
        "danny chan": "陈百强",
        "roman tam": "罗文"
    }
    
    q_artist_lower = artist.lower().strip()
    if q_artist_lower in PINYIN_ARTIST_MAP:
        artist = PINYIN_ARTIST_MAP[q_artist_lower]
        logger.info("Auto-translated Pinyin artist query to native Hanzi: '%s'", artist)

    key = _cache_key(artist, track)

    # 1. Cache hit
    cached = _get_cached(key)
    if cached:
        logger.info("Lyrics cache hit: %s | %s", artist, track)
        return cached

    # 2. Exact fetch
    raw = await fetch_lyrics_raw(artist, track)

    # 3. LRCLIB exact retry with CJK-only sub-title for bilingual tracks.
    # e.g. "A Short Story 一个短篇" → also try artist + "一个短篇"
    # Do NOT try the ASCII-only part ("A Short Story") — it may match unrelated English songs.
    if not raw:
        def _cjk_part(s: str) -> str:
            return re.sub(r'[^\u4e00-\u9fff\u3040-\u30ff\uac00-\ud7af\.]', '', s).strip()
        cjk_track = _cjk_part(track)
        if cjk_track and cjk_track != track:
            logger.info("LRCLIB exact retry (CJK only): '%s' – '%s'", artist, cjk_track)
            raw = await fetch_lyrics_raw(artist, cjk_track)

    # 3b. LRCLIB fuzzy search variants
    if not raw:
        logger.info("Falling back to LRCLIB search for '%s' – '%s'", artist, track)
        search_queries = [f"{artist} {track}"]
        cjk_track = re.sub(r'[^\u4e00-\u9fff\u3040-\u30ff\uac00-\ud7af\.]', '', track).strip()
        if cjk_track and cjk_track != track:
            search_queries.append(f"{artist} {cjk_track}")
            search_queries.append(cjk_track)

        reqs = [search_lyrics_raw(q) for q in search_queries]
        responses = await asyncio.gather(*reqs, return_exceptions=True)
        
        for q, candidate in zip(search_queries, responses):
            if isinstance(candidate, Exception) or not candidate:
                continue
            # Validate: reject LRCLIB results that don't match the actual track.
            # "I Love You" by a random English artist must NOT match "i love you 我爱你".
            result_track_name = candidate.get("trackName", "")
            result_artist_name = candidate.get("artistName", "")
            result_duration_ms = int(candidate.get("duration", 0) * 1000)
            if _is_valid_match(track, result_track_name, artist, result_artist_name, duration_ms, result_duration_ms):
                raw = candidate
                logger.info("LRCLIB fuzzy accepted (query='%s', result='%s')", q, result_track_name)
                break
            else:
                logger.info("LRCLIB fuzzy REJECTED (query='%s', result='%s' doesn't match '%s')", q, result_track_name, track)


    # 4. Fallbacks (Netease -> KuGou)
    source = "lrclib"
    synced_raw = ""
    plain_raw = None
    
    if raw:
        synced_raw = raw.get("syncedLyrics") or ""
        plain_raw = raw.get("plainLyrics") or None
        
    # If LRCLIB fails to find the track entirely, OR if it finds an entry but it only has PLAIN lyrics,
    # we heavily prioritize SYNCED lyrics, so we STILL execute the fallbacks to see if Netease has synced!
    if not synced_raw:
        logger.info("Executing Netease and KuGou fallbacks concurrently...")
        netease_task = asyncio.create_task(search_lyrics_netease(artist, track, duration_ms))
        kugou_task = asyncio.create_task(search_lyrics_kugou(artist, track, duration_ms))
        
        netease_lrc, kugou_lrc = await asyncio.gather(netease_task, kugou_task, return_exceptions=True)
        
        if isinstance(netease_lrc, str) and netease_lrc:
            synced_raw = netease_lrc
            source = "netease"
        elif isinstance(kugou_lrc, str) and kugou_lrc:
            synced_raw = kugou_lrc
            source = "kugou"

    # Build response
    synced_lines = parse_lrc(synced_raw) if synced_raw.strip() else []

    result = LyricsResponse(
        synced=synced_lines,
        plain=plain_raw,
        has_synced=len(synced_lines) > 0,
        source=source,
    )

    # Only persist to disk if we actually found lyrics — don't cache "not found"
    if synced_lines or plain_raw:
        _set_cache(key, result)
    else:
        _hot_cache[key] = result  # session-only, retried next startup

    return result
